(function(e,u){function g(){e[c]||(e[c]={});return e[c]}var c="app",b;b=g();b.namespace=b.ns=function(b,g){if(b){b=String(b);var p=b.split("."),m=p.length,t=e[c],r;t||(e[c]={});if(!p)return!1;for(r=0;r<m;r+=1)t[p[r]]||(t[p[r]]={}),r===m-1&&g!==u&&(t[p[r]]=g),t=t[p[r]];return t}return!1};e[c]=b;e.getNamespace=e.getNs=g})(window);
(function(e,u){function g(){if(!(this instanceof g))return new g;this.m=[];this.r=null;this.f=!1}g.prototype=g.fn={add:function(c){this.f?c(this.r):this.m.push(c)},flush:function(c){if(!this.f)for(this.r=c,this.f=!0;this.m[0];)this.m.shift()(c)}};e.ns("helpers.queue",g)})(window.getNs());
(function(e,u,g,c){var b=function(){var l=null,g=[];return{isString:function(b){return"string"===typeof b||b instanceof String},isFunction:function(b){return"function"===typeof b||b instanceof Function},isArray:function(c){var m=Array.isArray,e=Object.prototype.toString;b.isArray=m&&"function"===typeof m?function(b){return m(b)}:e&&"function"===e?function(b){return"[object Array]"===e.call(b)}:function(b){return!!b&&!!b.sort&&"function"===typeof b.sort};return b.isArray(c)},inArray:function(c,e,t){b.inArray=
Array.prototype.indexOf?function(b,c,h){return g.indexOf.call(c,b,h)}:function(b,c,h){var d=c.length,a=0;if(h)return c[h]&&c[h]===b?h:-1;for(a=0;a<d;a+=1)if(c[a]===b)return a;return-1};return b.inArray(c,e,t)},callback:function(p){b.isFunction(p)||(p=function(){return c});return p},on:function(c,m,t){b.on="function"===typeof e.addEventListener?function(b,c,h){b.addEventListener(c,h,!1)}:"function"===typeof u.attachEvent?function(b,c,h){b.attachEvent("on"+c,h)}:function(b,c,h){b["on"+c]=h};b.on(c,
m,t)},off:function(c,m,t){b.off="function"===typeof e.removeEventListener?function(b,c,h){b.removeEventListener(c,h,!1)}:"function"===typeof u.detachEvent?function(b,c,h){b.detachEvent("on"+c,h)}:function(b,c){b["on"+c]=null};b.off(c,m,t)},getXhr:function(){for(var b=null,c=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],e=c.length,l=0,l=0;l<
e;l+=1){try{b=c[l]()}catch(g){continue}break}return b},xhr:function(e,m,l,g){var q=b.getXhr(),h,d="GET";m=b.callback(m);if(q)if(e){g!==c?d="POST":g=null;l===c&&(l=!0);h=function(){if(4===q.readyState&&(200<=q.status&&400>q.status||0===q.status))try{var a=q.responseText;a?m(a):m(!1)}catch(b){m(!1)}else 4===q.readyState&&m(!1)};q.open(d,e,l);try{q.onreadystatechange!==c?q.onreadystatechange=h:q.onload!==c&&(q.onload=h)}catch(a){}q.send(g)}else m(!1);else m(!1)},getJson:function(){null===l&&(e.JSON&&
e.JSON.stringify)&&(l=e.JSON);return l},jsonToString:function(e){var m=!1;null===l&&(l=b.getJson());l&&e!==c&&(m=l.stringify(e));return m},jsonToObject:function(e){var m=!1;null===l&&(l=b.getJson());l&&e!==c&&(m=l.parse(e));return m},logToScreen:function(b){var c=u.getElementById("log"),e=u.createElement("p");b=u.createTextNode(b);c&&(e.appendChild(b),c.appendChild(e))},log:function(){var l=arguments,m=e.console!==c,g=m?e.console:null,m=m&&g.log!==c;l.length&&(m&&(g.log.apply?g.log.apply(g,l):g.log(l)),
l=l[0],b.logToScreen(l))},url:function(c){if(b.isString(c)){var e=u.createElement("a"),l;e.href=c;l=e.pathname.match(/\/([^\/?#]+)$/i);return{source:c,protocol:e.protocol,host:e.hostname,port:e.port,query:e.search,file:l?l[1]:"/",hash:e.hash,path:e.pathname.replace(/^([^\/])/,"/$1"),extension:function(b){b=b.split(".");return b.length?b[b.length-1]:!1}(c),folder:function(){var b=c.lastIndexOf("/");return c.substr(0,b+1)}()}}},trim:function(c){if(!b.isString(c))return c;b.isFunction(String.prototype.trim)||
(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});return c.trim()}}}();g.ns("helpers.utils",b)})(window,document,window.getNs());
(function(e,u,g,c){var b=function(){function b(){m===c&&(q(e,"online",b),q(e,"offline",b));m=u.onLine!==c?!!u.onLine:!0}var s,p,m,t,r=(u.userAgent||u.vendor||e.opera).toLowerCase(),q=g.helpers.utils.on;return{isMsie:function(){p===c&&(p=null!==r.match(/(msie)/));return p},isOpera:function(){s===c&&(s=null!==r.match(/(opera)/));return s},isOnline:function(){m===c&&b();return m},hasCanvas:function(){if(t===c){var b=document.createElement("canvas");t=!(!b.getContext||!b.getContext("2d"))}return t}}}();
g.ns("helpers.client",b)})(window,window.navigator,window.getNs());
(function(e,u,g){function c(b,c){c&&(c.dom?b=c.dom:c.id&&(b=e.getElementById(c.id)));return b}var b=function(){var l=u.helpers,s=l.utils,p=l.client,m=[],t=[],r=[],q=[],h=e.getElementsByTagName("head")[0];return{nuke:function(){m=[];t=[];r=[];q=[]},createDomNode:function(b,a){var k=e.createElement(b),c;if(a)for(c in a)a.hasOwnProperty(c)&&k.setAttribute(c,a[c]);return k},getAttribute:function(b,a){return b.getAttribute(a)},setAttribute:function(b,a,c){b.setAttribute(a,c)},appendCss:function(d,a,k,
x,f){if(-1===s.inArray(d,m)||f){var n=null,w=!1,v,l,n=c(n,x);if(null!==a){n||(n=b.createDomNode("style",{type:"text/css"}),n.className="lazyloaded");n.onerror=function(){k(!1)};x||h.appendChild(n);try{v=e.createTextNode(a),n.appendChild(v)}catch(g){n.styleSheet.cssText=a}finally{k(!0)}}else null!==d&&(n||(n=b.createDomNode("link",{rel:"stylesheet",type:"text/css"}),n.className="lazyloaded"),n.onerror=n.error=function(){n.onload=n.load=null;w=!0;window.clearTimeout(l);k(!1)},x||h.appendChild(n),p.isMsie()||
p.isOpera()?n.onload=n.load=function(){n.onerror=n.error=null;w=!0;window.clearTimeout(l);k(!0)}:k(!0),n.href=d,l=window.setTimeout(function(){w||k(!1)},4E3));m.push(d)}else k(!0)},appendJs:function(d,a,k,x,f){if(-1===s.inArray(d,t)||f){f=b.createDomNode("script");var n=e.getElementsByTagName("script")[0],w=!1,v=!1,l;(f=c(f,x))?(f.type="text/javascript",f.className="lazyloaded",f.async=!0,f.onreadystatechange=f.onload=function(){v||this.readyState&&"complete"!==this.readyState&&"loaded"!==this.readyState||
(this.onreadystatechange=this.onload=null,w=v=!0,window.clearTimeout(l),t.push(d),k(!0))},f.onerror=function(){this.onload=this.onreadystatechange=this.onerror=null;window.clearTimeout(l);w=!0;k(!1)},x||(n?n.parentNode.insertBefore(f,n):h.appendChild(f)),a&&!v?(f.textContent?f.textContent=a:f.nodeValue?f.nodeValue=a:f.text=a,w=v=!0):null!==d&&(f.src=d),v&&(t.push(d),w=!0,k(!0)),w||(l=window.setTimeout(function(){v||k(!1)},5E3))):k(!1)}else k(!0)},appendImg:function(b,a,k,h){var f=null;(f=c(f,h))||
(f=new Image);f.onerror=function(){f.onload=f.onerror=null;k(!1)};f.onload=function(){f.onload=f.onerror=null;k(!0)};a?f.src=a:b&&(f.src=b);if(f.complete&&f.naturalWidth!==g)f.onload();r.push(b)},appendHtml:function(b,a,k,h){var f=c(null,h);if(f){if(a)try{f.innerHTML=a,h.id&&p.isMsie()&&e.styleSheets[0].addRule("#"+h.id+":after",'content: " ";')}catch(n){f.innerText=a}k(!0);q.push(b)}else k(!1)}}}();u.ns("helpers.dom",b)})(document,window.getNs());
(function(e,u,g){function c(a){r("["+m+" Adapter] "+a)}function b(a){if(a){var b=a.name||a.code,h=a.message||a.description||"",f=h;if(FileError)switch(b){case FileError.ENCODING_ERR:case "EncodingError":f="Error Event: ENCODING_ERR "+h;break;case FileError.INVALID_MODIFICATION_ERR:case "InvalidModificationError":f="Error Event: INVALID_MODIFICATION_ERR";break;case FileError.INVALID_STATE_ERR:case "InvalidStateError":f="Error Event: INVALID_STATE_ERR "+h;break;case FileError.NO_MODIFICATION_ALLOWED_ERR:case "NoModificationAllowedError":f=
"Error Event: NO_MODIFICATION_ALLOWED_ERR "+h;break;case FileError.NOT_FOUND_ERR:case "NotFoundError":f="Error Event: NOT_FOUND_ERR "+h;break;case FileError.NOT_READABLE_ERR:case "NotReadableError":f="Error Event: NOT_READABLE_ERR "+h;break;case FileError.PATH_EXISTS_ERR:case "PathExistsError":f="Error Event: PATH_EXISTS_ERR "+h;break;case FileError.QUOTA_EXCEEDED_ERR:case "QuotaExceededError":f="Error Event: QUOTA_EXCEEDED_ERR "+h;break;case FileError.SECURITY_ERR:case "SecurityError":f="Error Event: SECURITY_ERR "+
h;break;case FileError.TYPE_MISMATCH_ERR:case "TypeMismatchError":f="Error Event: TYPE_MISMATCH_ERR "+h;break;default:f="Error Event: Unknown Error "+h}else f="Error Event: Unknown Error, no FileError available";c(f,a)}}function l(a,h,c){var f=function(a){b(a);c(!1)};if("."===h[0]||""===h[0])h=h.slice(1);h[0]?a.getDirectory(h[0],{create:!0},function(a){h.length?l(a,h.slice(1),c):c(!0)},f):c(!0)}function s(a,b,h){b=b.split("/");var f=b.length,c="",d=0;h=q(h);if(f){for(d=0;d<f-1;d+=1)c=c+b[d]+"/";l(a.root,
c.split("/"),h)}else h(!0)}function p(a){if(!(this instanceof p))return new p(a);this.adapter=null;this.type=m;this.size=52428800;this.init(a)}var m="fileSystem",t=u.helpers.utils,r=t.log,q=t.callback,h=null,d=e.requestFileSystem||e.webkitRequestFileSystem||e.moz_requestFileSystem;p.prototype=p.fn={isSupported:function(){null===h&&((h=!!d&&(!!e.Blob||!!e.BlobBuilder)&&e.FileReader)||c(m+" is not supported"));return h},open:function(a){var k=this,x=k.adapter,f=function(f){b(f);a(!1)};a=q(a);h?null===
x?(e.requestFileSystem=d,e.requestFileSystem(e.TEMPORARY,k.size,function(b){x=k.adapter=b;c("Try to create test resource");try{k.create("test-item",t.jsonToString({test:"test-content"}),function(b){b?k.remove("test-item",function(){c("Test resource created and successfully deleted");a(x)}):f()})}catch(h){f(h)}},f)):(c("Adapter already opened"),a(x)):a(!1)},create:function(a,k,d){d=q(d);if(a&&h){var f=this.adapter,n=function(a){b(a);d(!1,a)};s(f,a,function(){f.root.getFile(a,{create:!0},function(b){b.createWriter(function(b){var f;
b.onwriteend=function(){c("File successfully written: url "+a);d(!0)};b.onerror=n;try{Blob?(f=new Blob([k],{type:"text/plain"}),b.write(f)):BlobBuilder&&(f=new BlobBuilder,f.append(k),b.write(f.getBlob("application/json")))}catch(h){n(h)}},n)},n)})}else d(!1)},read:function(a,c){c=q(c);if(a&&h){var d=this.adapter,f=function(a){b(a);c(!1,a)};s(d,a,function(){d.root.getFile(a,{create:!1},function(a){a.file(function(a){var b=new FileReader;b.onloadend=function(){c(this.result)};b.onerror=f;b.onabort=
f;b.readAsText(a)},f)},f)})}else c(!1)},update:function(a,b,h){this.create(a,b,h)},remove:function(a,c){c=q(c);if(a&&h){var d=this.adapter,f=function(a){b(a);c(!1,a)};s(d,a,function(){d.root.getFile(a,{create:!1},function(a){a.remove(function(){c(!0)},f)},f)})}else c(!1)},init:function(a){return this.isSupported()?(a&&a.size&&(this.size=a.size),this):!1}};u.ns("cache.storage.adapter."+m,p)})(window,window.getNs());
(function(e,u,g){function c(b){m("["+s+" Adapter] "+b)}function b(b){b&&c("Database error: "+(b.message||" No message avaible"))}function l(b){if(!(this instanceof l))return new l(b);this.adapter=null;this.type=s;this.dbName="cache";this.dbVersion="1.0";this.dbTable="offline";this.dbDescription="offline cache";this.dbKey="key";this.init(b)}var s="indexedDatabase",p=u.helpers.utils,m=p.log,t=p.callback,r=null,q=e.indexedDB||e.webkitIndexedDB||e.mozIndexedDB||e.OIndexedDB||e.msIndexedDB;l.prototype=
l.fn={isSupported:function(){null===r&&((r=!!q)||c(s+" is not supported"));return r},create:function(h,d,a){a=t(a);if(h&&r){var k=this.dbTable,e=this.dbName,f=this.adapter.transaction([k],"readwrite");h=f.objectStore(k).put({key:h,content:d});f.onerror=function(f){c("Failed to init transaction while creating/updating database entry "+e+" "+f);b(f);a(!1,f)};h.onerror=function(f){c("Failed to create/update database entry "+e+" "+f);b(f);a(!1,f)};h.onsuccess=function(){a(!0)}}else a(!1)},read:function(h,
d){d=t(d);if(h&&r){var a=this.dbTable,k=this.dbName,e=this.adapter.transaction([a],"readonly"),a=e.objectStore(a).get(h);e&&a?(e.onerror=function(a){c("Failed to init transaction while reading database "+k+" "+a);b(a);d(!1,a)},a.onerror=function(a){c("Failed to read database entry "+k+" "+a);b(a);d(!1,a)},a.onsuccess=function(a){a.target.result&&a.target.result.content?d(a.target.result.content):d(!1)}):d(!1)}else d(!1)},update:function(b,c,a){this.create(b,c,a)},remove:function(h,d){d=t(d);if(h&&
r){var a=this.dbTable,k=this.dbName,e=this.adapter.transaction([a],"readwrite"),a=e.objectStore(a).put({key:h,content:""});e.onerror=function(a){c("Failed to init transaction while deleting database entry "+k+" "+a);b(a);d(!1,a)};a.onerror=function(a){c("Failed to delete database entry "+k+" "+a);b(a);d(!1,a)};a.onsuccess=function(){d(!0)}}else d(!1)},open:function(h,d){d||(d=!1);h=t(h);var a=this,k=null,l=null,f=null,n=a.dbName,w=a.dbTable,v=function(b){b||h(!1);c("Try to create test resource");
a.create("test-item",'{test: "test-content"}',function(f){f?a.remove("test-item",function(){c("Test resource created and successfully deleted");h(b)}):h(!1)})},m,p,z,r,y;if(null===a.adapter)if(k=q){e.webkitIndexedDB!==g&&(e.IDBTransaction=e.webkitIDBTransaction,e.IDBKeyRange=e.webkitIDBKeyRange);m=function(b){b.createIndex(a.dbKey,a.dbKey,{unique:!0});b.createIndex("content","content",{unique:!1})};p=function(d){var k=l.result,e,g;a.adapter=k;c("Database request successfully done");a.dbVersion===
k.version||!k.setVersion&&"function"!==typeof k.setVersion?(a.adapter=k,v(k)):(f=d.currentTarget.result.setVersion(a.dbVersion),f.onfailure=function(a){c("Failed to open database: "+n+" "+a);b(a);h(!1)},f.onsuccess=function(f){e=l.result;try{g=e.createObjectStore(w,{keyPath:a.dbKey}),c("Database needs upgrade: "+n+" "+f.oldVersion+" "+f.newVersion),m(g)}catch(k){c("Failed to open database: "+n+" "+k),b(k),h(!1)}})};z=function(b){var f=l.result.createObjectStore(w,{keyPath:a.dbKey});c("Database needs upgrade: "+
n+" "+b.oldVersion+" "+b.newVersion);m(f)};r=function(f){c("Failed to open database: "+n+" "+f);b(f);d||a.open(h,!0);h(!1)};y=function(a){c("Opening database request is blocked! "+n+" "+a);b(a);h(!1)};if(d)try{l=k.open(n,a.dbVersion)}catch(u){c("Could not set version"),b(u),l=k.open(n)}else l=k.open(n);l.onsuccess=p;l.onupgradeneeded=z;l.onerror=r;l.onblocked=y}else h(!1);else v(a.adapter)},init:function(b){return this.isSupported()?(b&&(b.name&&(this.dbName=String(b.name)),b.version&&(this.dbVersion=
parseInt(b.version,10)),b.table&&(this.dbTable=b.table),b.description&&(this.dbDescription=String(b.description)),b.key&&(this.dbKey=b.key)),this):!1}};u.ns("cache.storage.adapter."+s,l)})(window,window.getNs());
(function(e,u,g){function c(b){m("["+p+" Adapter] "+b)}function b(b,c,a,k,e,f){!f&&b?b.transaction(function(b){b.executeSql(c,a,k,e)}):f?f.executeSql(c,a,k,e):e(null,{code:0,message:p+" isn't available"})}function l(b){var d="Errorcode: "+(b.code||"Code not present")+", Message: "+(b.message||"Message not present");b.info&&(d=d+" - "+b.info);c(d)}function s(b){if(!(this instanceof s))return new s(b);this.adapter=null;this.type=p;this.dbName="cache";this.dbVersion="1.0";this.dbDescription="resource cache";
this.dbTable="websql";this.dbSize=4194304;this.init(b)}var p="webSqlDatabase";g=u.helpers.utils;var m=g.log,t=g.callback,r=null,q=e.openDatabase;s.prototype=s.fn={isSupported:function(){null===r&&((r=!!q)||c(p+" is not supported"));return r},create:function(c,d,a){a=t(a);c&&r?b(this.adapter,"INSERT INTO "+this.dbTable+" (key, content) VALUES (?,?);",[c,d],function(){a(!0)},function(b,c){l(c);a(!1,c,{transaction:b})}):a(!1)},read:function(c,d){d=t(d);c&&r?b(this.adapter,"SELECT content FROM "+this.dbTable+
" WHERE key=?;",[c],function(a,b){var c=!1;b&&(b.rows&&1===b.rows.length)&&(c=b.rows.item(0).content);d(c,null,{transaction:a})},function(a,b){l(b);d(!1,b,{transaction:a})}):d(!1)},update:function(c,d,a){a=t(a);c&&r?b(this.adapter,"UPDATE "+this.dbTable+" SET content = ?  WHERE key=?;",[d,c],function(){a(!0)},function(b,c){l(c);a(!1,c,{transaction:b})}):a(!1)},remove:function(c,d){d=t(d);c&&r?b(this.adapter,"DELETE FROM "+this.dbTable+" WHERE key = ?;",[c],function(){d(!0)},function(a,b){l(b);d(!1,
b,{transaction:a})}):d(!1)},open:function(h){h=t(h);if(r){var d=this,a=d.adapter,k,g=function(a){a||h(!1);c("Try to create test resource");k=function(b){b?d.remove("test-item",function(){c("Test resource created and successfully deleted");h(a)}):h(!1)};d.read("test-item",function(a){a?d.update("test-item",'{test: "test-content"}',k):d.create("test-item",'{test: "test-content"}',k)})},f=function(a,f){c("Checking database table: name "+d.dbTable);b(a,"CREATE TABLE IF NOT EXISTS "+d.dbTable+"(id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, key TEXT NOT NULL UNIQUE, content TEXT NOT NULL);",
[],function(){g(d.adapter)},function(a){l(a);g(!1)},f)},n=function(a){f(null,a)},w=function(a){a.info="Can't migrate to new database version. This may be caused by non-standard implementation of the changeVersion method. Please switch back your database version to use webSql on this device.";l(a);h(!1)};try{if(null===a&&d.isSupported())if(c("Initializing database"),d.adapter=a=q(d.dbName,"",d.dbDescription,d.dbSize),String(a.version)!==String(d.dbVersion)&&a.changeVersion&&"function"===typeof a.changeVersion){c("Try to update version: new version "+
a.version+", old version "+d.dbVersion);try{a.changeVersion(a.version,d.dbVersion,n,w)}catch(v){l(v),h(!1)}}else c("Open database with version number: "+d.dbVersion),a=e.openDatabase(d.dbName,d.dbVersion,d.dbDescription,d.dbSize),f(a);else d.isSupported()&&(c("database already initialized"),g(a))}catch(m){l(m),h(!1)}}else h(!1)},init:function(b){return this.isSupported()?(b&&(b.description&&(this.dbDescription=b.description),b.name&&(this.dbName=b.name),b.size&&(this.dbSize=b.size),b.table&&(this.dbTable=
b.table),b.version&&(this.dbVersion=String(b.version))),this):!1}};u.ns("cache.storage.adapter."+p,s)})(window,window.getNs());
(function(e,u,g){function c(a){r("["+p+" Adapter] "+a)}function b(a){!a&&e.event&&(a=e.event);c("Event - key: "+(a.key||"no e.key event")+", url: "+(a.url||"no e.url event"))}function l(a){a=q(a);switch(a){case "local":a="localStorage";break;case "session":a="sessionStorage";break;default:a="localStorage"}return a}function s(a){if(!(this instanceof s))return new s(a);this.adapter=null;this.type=p;this.lifetime="local";this.asynch=!0;this.init(a)}var p="webStorage",m=u.helpers.utils,t=m.on,r=m.log,
q=m.trim,h=m.callback,d=null;s.prototype=s.fn={isSupported:function(){var a=l(this.lifetime);if(null===d)try{d=!!e[a]&&!!e[a].getItem}catch(b){c(p+" is not supported",b),d=!1}return d},create:function(a,c,d){var f=this,e=!0,l=function(a){if(f.asynch)d(a);else return a};d=h(d);if(!a)return l(!1);try{f.adapter.setItem(a,c)}catch(v){e=!e,b(v)}return l(e)},read:function(a,c){var d=this,f,e=!0,l=function(a){if(d.asynch)c(a);else return a};c=h(c);if(!a)return l(!1);try{e=(f=d.adapter.getItem(a))?f:!1}catch(v){e=
!e,b(v)}return l(e)},update:function(a,b,c){if(this.asynch)this.create(a,b,c);else return this.create(a,b,c)},remove:function(a,c){var e=this,f=!0,d=function(a){if(e.asynch)c(a);else return a};c=h(c);if(!a)return d(!1);try{e.adapter.removeItem(a)}catch(l){f=!f,b(l)}return d(f)},open:function(a){var d=this,g=d.adapter,f=l(d.lifetime),n,m,v=function(b){if(d.asynch)a(b);else return b};a=h(a);if(null===g)try{if(g=d.adapter=e[f],t(e,"storage",b),c("Lifetime used: "+f),c("Try to create test resource"),
d.asynch)d.create("test-item",'{test: "test-content"}',function(b){b?d.remove("test-item",function(){c("Test resource created and successfully deleted");a(g)}):a(!1)});else{if(n=d.create("test-item",'{test: "test-content"}'))if(m=d.remove("test-item"))return c("Test resource created and successfully deleted"),g;return!1}}catch(p){return b(p),v(!1)}else if(d.isSupported())return v(g)},init:function(a){return this.isSupported()?(a&&(a.lifetime&&(this.lifetime=q(String(a.lifetime))),a.asynch!==g&&(this.asynch=
!!a.asynch)),this):!1}};u.ns("cache.storage.adapter."+p,s)})(window,window.getNs());
(function(e,u,g,c){function b(a){h("["+p+" Adapter] "+a)}function l(a,c){c.isLoaded||(c.isLoaded=!0,c.progressCallback(100),e.setTimeout(function(){a();b("Event loaded")},c.delay))}function s(a){if(!(this instanceof s))return new s(a);this.adapter=null;this.type=p;this.isLoaded=!1;this.delay=0;this.opened=!0;this.message="New version available. Update page?";this.init(a)}var p="applicationCache",m=g.helpers,t=m.utils,r=m.dom,q=t.on,h=t.log,d=t.callback,a=null,k=u.getElementsByTagName("html")[0],x=
e.applicationCache;s.prototype=s.fn={isSupported:function(){null===a&&((a=!!x&&!!r.getAttribute(k,"manifest"))||b(p+" is not supported or there is no manifest html attribute"));return a},open:function(a,h){var k=this,g=k.adapter,m=0,p,z;k.opened=!0;a=d(a);h&&h.progress&&(p=h.progress);p=k.progressCallback=d(p);if(k.isSupported()&&null!==g){z=function(){b("Event updateready");try{g.swapCache()}catch(c){b("Event updateready: swapcache is not available",c)}confirm(k.message)?e.location.reload(!0):l(a,
k);return!1};q(g,"checking",function(){b("Event checking");return!1});q(g,"noupdate",function(){b("Event noupdate");l(a,k);return!1});q(g,"downloading",function(){b("Event downloading");m=0;return!1});q(g,"progress",function(a){b("Event progress");var f=0;k.delay=500;m+=1;f=a&&a.lengthComputable!==c?Math.round(100*a.loaded/a.total):Math.round(100*m/20);p(f);return!1});q(g,"cached",function(){b("Event cached");l(a,k);return!1});q(g,"updateready",function(){z()});q(g,"obsolete",function(){b("Event obsolete");
e.location.reload(!0);return!1});q(g,"error",function(){b("Event error");l(a,k);return!1});switch(g.status){case g.UNCACHED:l(a,k);break;case g.IDLE:l(a,k);break;case g.UPDATEREADY:z();break;case g.OBSOLETE:l(a,k)}q(e,"online",function(){try{g.update()}catch(a){b("Window event online: update cache is not available",a)}});e.setTimeout(function(){k.isLoaded||l(a,k)},12E3)}else l(a,k)},init:function(a){this.isSupported()&&(null===this.adapter&&(this.adapter=x),a&&(a.message&&(this.message=String(a.message)),
a.delay!==c&&(this.delay=parseInt(a.delay,10))));return this}};g.ns("cache.storage.adapter."+p,s)})(window,document,window.getNs());
(function(e,u,g,c){function b(a){F("["+x+" controller] "+a)}function l(a){var c="";a&&(c="Error Event: Description "+(a.description||"no description available"));b(c)}function s(a,b,c){c.timeout=e.setTimeout(function(){b(!1)},4E3);I(a,function(a){e.clearTimeout(c.timeout);delete c.timeout;a?b(a):b(!1)})}function p(a){var c=null;try{c=w.jsonToObject(a)}catch(f){l(f),b("Couldn't convert json string to object.")}return c}function m(a,b,f){if(G){var d=u.createElement("canvas"),e,h=new Image,k=null,l=
0,g=0;f||(f="jpeg");h.onerror=function(){h.onload=h.onerror=null;b()};h.onload=function(){h.onload=h.onerror=null;l=d.height=h.height;g=d.width=h.width;e=d.getContext("2d");e.fillStyle="rgba(50, 50, 50, 0)";e.fillRect(0,0,g,l);e.drawImage(h,0,0);k=d.toDataURL("image/"+f);b(k)};h.src=a;if(h.complete&&h.naturalWidth!==c)h.onload()}else b(!1)}function t(a){var b=a.data,c=a.url;"css"===a.type&&(c=w.url(c),c=c.folder,b=b.replace(/url\(\../g,"url("+c+".."),b=b.replace(/url\(\'../g,"url('"+c+".."),b=b.replace(/url\(\"../g,
'url("'+c+".."),a.data=b);return a}function r(a,b){return{ajax:a.ajax,data:a.data,expires:(new Date).getTime()+(a.lifetime||b.lifetime),group:a.group!==c?a.group:b.group,lastmod:a.lastmod||b.lastmod,lifetime:a.lifetime!==c?a.lifetime:b.lifetime,type:a.type||b.type,version:a.version||b.version}}function q(a,b,c){var f=a.type,d=a.url,e=a.data;a.ajax?"img"===f?m(d,b):s(d,b,a):e?b(e):c(!1)}function h(a){return B&&B[a]?!!B[a]:!1}function d(a,c){var f=null,e,h;a&&a.length?(e=a[0].type,h=a.slice(1),b("Testing for storage adapter type: "+
e),C[e]?f=new C[e](E):d(h,c),f&&f.isSupported()?f.open(function(k){k?(D=e,B=a[0],b("Used storage adapter type: "+D),c(f)):d(h,c)}):d(h,c)):c(!1)}function a(c,f,e){var h=null,k=0,g;if(e)try{b("Testing for preferred storage adapter type: "+e),C[e]?(h=new C[e](E))&&h.isSupported()?h.open(function(d){if(d){D=e;g=f.length;for(k=0;k<g;k+=1)f[k].type===e&&(B=f[k]);B?(b("Used storage type: "+D),c(h)):(b("Storage config not found: "+D),a(c,f))}else a(c,f)}):a(c,f):a(c,f)}catch(n){l(n),b("Storage adapter could not be initialized: type "+
e),a(c,f)}else d(f,c)}function k(a,b){if(!(this instanceof k))return new k(a,b);this.isEnabled=!0;this.appCacheAdapter=this.adapter=null;this.adapters={types:H,defaults:E};this.resources={defaults:J};this.init(a,b)}var x="storage",f=g.helpers,n=f.client,w=f.utils,v=w.isArray,F=w.log,A=w.callback,z=w.getJson(),I=w.xhr,y=w.trim,C=g.cache.storage.adapter,G=n.hasCanvas(),H=[{type:"fileSystem",css:!0,js:!0,html:!0,img:!0},{type:"indexedDatabase",css:!0,js:!0,html:!0,img:!0},{type:"webSqlDatabase",css:!0,
js:!0,html:!0,img:!0},{type:"webStorage",css:!0,js:!0,html:!0,img:!0}],E={name:"localcache",table:"cache",description:"local resource cache",size:4194304,version:"1.0",key:"key",lifetime:"local",offline:!0},D=null,B=null,J={ajax:!0,lifetime:2E4,group:0,lastmod:(new Date).getTime(),type:"css",version:1};k.prototype=k.fn={create:function(a,c){c=A(c);if(a&&a.url){var f=this,e=a.url,d=a.type;q(a,function(k){if(k)if(a.data=k,a=t(a),null!==f.adapter&&h(d)){k=w.jsonToString(e);var g=r(a,f.resources.defaults),
n=w.jsonToString(g);a.expires=g.expires;a.version=g.version;try{f.adapter.create(k,n,function(f){f?(b("Create new resource in storage adapter: type "+d+", url "+e),c(a)):(b("Create new resource in storage adapter failed"),c(!1))})}catch(m){l(m),b("Create new resource in storage adapter failed"),c(a)}}else b("Trying to create new resource, but resource type is not cachable or storage adapter is not available: type "+d+", url "+e),c(a);else b("Couldn't get data via network"),c(a)},c)}else c(!1)},read:function(a,
c){c=A(c);if(a&&a.url){var f=this,e=a.url,d=a.type;if(null!==this.adapter&&h(d)){b("Trying to read resource from storage: type "+d+", url "+e);try{f.adapter.read(w.jsonToString(e),function(h){h?(a=p(h))?(a.url=e,b("Successfully read resource from storage: type "+d+", url "+e),c(a,!0)):f.remove({url:e,type:d},function(){c(!1)}):(b("There is no data coming back from storage while reading: type "+d+", url "+e),c(!1))})}catch(k){l(k),b("Try to read resource from storage, but storage adapter is not available: type "+
d+", url "+e),s(e,function(f){b("Data loaded via ajax: type "+d+", url "+e+", data status "+!!f);a.data=f;c(a,!0)},a)}}else c(a)}else c(!1)},update:function(a,c){c=A(c);if(a&&a.url){var f=this,e=a.url,d=a.type;q(a,function(k){if(k)if(a.data=k,a=t(a),null!==f.adapter&&h(d)){k=w.jsonToString(e);var g=r(a,f.resources.defaults),n=w.jsonToString(g);a.expires=g.expires;a.version=g.version;try{f.adapter.update(k,n,function(f){f?(b("Updated existing resource in storage adapter: type "+d+", url "+e),c(a)):
(b("Updating resource in storage failed."),c(!1))})}catch(m){l(m),b("Updating resource in storage failed."),c(a)}}else b("Resource type is not cachable or storage adapter is not available: type "+d+", url "+e),c(a);else b("Couldn't get data via network, trying to used stored version"),f.read(a,function(b){b&&b.data?(a.data=b.data,c(a)):c(!1)})},c)}else c(!1)},remove:function(a,c){c=A(c);if(a&&a.url){var f=a.url,e=a.type;null!==this.adapter&&h(e)?this.adapter.remove(w.jsonToString(f),function(d){d?
(b("Delete resource form storage: type "+e+", url "+f),c(a)):(b("Deleting resource form storage failed: type "+e+", url "+f),c(!1))}):(b("Delete resource from storage failed, resource type is not cachable or there is no storage adapter: type "+e+", url "+f),c(a))}else c(!1)},init:function(f,e){var d=this,h=!1,k,g,l,n;f=A(f);e&&e.isEnabled!==c&&(d.isEnabled=!!e.isEnabled);if(d.isEnabled&&z){if(e){if(e.adapters){k=e.adapters;if(k.types&&v(k.types)){g=k.types;l=g.length;for(n=0;n<l;n+=1)g[n].css===c&&
(g[n].css=!0),g[n].js===c&&(g[n].js=!0),g[n].img===c&&(g[n].img=!0),g[n].html===c&&(g[n].html=!0);d.adapters.types=g}k.defaults&&(g=k.defaults,l=d.adapters.defaults,g.name&&(l.name=y(String(g.name))),g.table&&(l.table=y(String(g.table))),g.description&&(l.description=y(String(g.description))),g.size&&(l.size=parseInt(g.size,10)),g.version&&(l.version=y(String(g.version))),g.key&&(l.key=y(String(g.key))),g.lifetime&&(l.lifetime=y(String(g.lifetime))),g.offline!==c&&(l.offline=!!g.offline));k.preferredType&&
(h=y(String(k.preferredType)))}e.resources&&(k=e.resources,k.defaults&&(k=k.defaults,g=d.resources.defaults,k.ajax!==c&&(g.ajax=!!k.ajax),k.lifetime!==c&&(g.lifetime=parseInt(k.lifetime,10)),k.group!==c&&(g.group=parseInt(k.group,10)),k.lastmod!==c&&(g.lastmod=parseInt(k.lastmod,10)),k.type&&(g.type=y(String(k.type))),k.group!==c&&(g.version=parseFloat(k.version)),k.loaded&&(g.loaded=A(k.loaded))))}a(function(a){a||(d.isEnabled=!1);d.adapter=a;f(d)},d.adapters.types,h);d.adapters.defaults.offline&&
(C.applicationCache&&!d.appCacheAdapter)&&(d.appCacheAdapter=new C.applicationCache(E))}else z||b("There is no json support"),d.isEnabled||b("Caching data is disabled"),f(d)}};g.ns("cache."+x+".controller",k)})(window,document,window.getNs());
(function(e,u){function g(a){r("["+l+" controller] "+a)}function c(a){var b=h(a.type);if("js"!==b||"css"!==b||"html"!==b||"img"!==b||"custom"!==b){switch(m.url(a.url).extension){case "js":a="js";break;case "css":a="css";break;case "html":a="html";break;case "jpg":case "jpeg":case "png":a="img";break;default:a="custom"}b=a}return b}function b(a,c){if(!(this instanceof b))return new b(a,c);this.storage=null;this.init(a,c)}var l="cache",s=e.helpers,p=s.dom,m=s.utils,t=s.client,r=m.log,q=m.isArray,h=
m.trim,d=m.callback;b.prototype=b.fn={load:function(a,b){var e=this,f=(new Date).getTime(),l=function(){var a=0,b=0,c=null;return{init:function(f,e){c=e;a=f;b=0},loaded:function(){b+=1;b===a&&c()}}}(),m=function(a,b,c){var f=a.url,e=function(){a.loaded(a);l.loaded()},d=a.node||null;c=!!c;switch(a.type){case "js":p.appendJs(f,b,e,d,c);break;case "css":p.appendCss(f,b,e,d,c);break;case "img":p.appendImg(f,b,e,d,c);break;case "html":p.appendHtml(f,b,e,d,c);break;default:g("Didn't match any type for dom append: type "+
a.type),e()}},v=function(a){var b=a.data||null,c=function(a,b){a&&a.data?m(a,a.data,b):m(a,null,b)},h=e.storage,k=h.resources.defaults;a.ajax=a.ajax!==u?!!a.ajax:k.ajax;a.loaded=a.loaded!==u?d(a.loaded):d(k.loaded);h.read(a,function(d){if(d&&d.data){var k=a,l=e.storage.resources.defaults,n=parseInt(d.lifetime,10),p=d.version,v=d.lastmod?d.lastmod:0,q=!1,r,s=k.lastmod?k.lastmod:0,q=!0;r=!1;k.version=r=k.version!==u?parseFloat(k.version):l.version;k.group=k.group!==u?parseFloat(k.group):l.group;s&&
v?(k.lastmod=parseInt(s,10),q=v===k.lastmod):!s&&v?s=v:s||(s=l.lastmod);q=q&&r===p;r=0!==n&&(-1!==n&&q&&d.expires>f||-1===n&&q);k.lastmod=s;k.isValid=r;a=k;a.isValid||!t.isOnline()?(g("Resource is up to date: type "+a.type+", url "+a.url),(b=d.data)&&m(a,b)):(g("Resource is outdated and needs update: type "+a.type+", url "+a.url),h.update(a,c))}else g("Resource or resource data is not available in storage adapter, try to create it: type "+a.type+", url "+a.url),h.create(a,c)})},r=function(a,b){var f=
0,d=a.length,e=null;l.init(d,b);for(f=0;f<d;f+=1)(e=a[f])&&e.url&&(e.url=h(e.url),e.type=c(e),v(e))},s=function(a,b,c){var f=a.length;for(c||(c=0);!a[c]&&c<f;)c+=1;c>=f?b(e):(f=a[c],r(f,function(){s(a,b,c+1)}))};(function(a,c){var f;a&&q(a)||(a=[]);f=a.length;for(var e=a,h=[],l,n=0,m,v=e.length,n=0;n<v;n+=1)m=e[n],(l=m.group)||(l=0),l=h[l]?h[l]:h[l]=[],l.push(m);a=h;c=d(b);g("Load resource function called: "+f+" resources, "+a.length+" groups");s(a,c)})(a,b)},remove:function(a,b){var e=this.storage,
f=function(a,b){var f=a.length,d,k,l=function(a,c){g("Successfully removed resource: url "+c);a===f-1&&b()};if(f)for(d=0;d<f;d+=1)(k=a[d])&&k.url&&(k.url=h(k.url),k.type=c(k),e.remove(k,l(d,k.url)));else b()};(function(a,c){a&&q(a)||(a=[]);c=d(b);g("Remove resource function called: resources count "+a.length);f(a,c)})(a,b)},init:function(a,b){var c=this;a=d(a);g("Cache initializing, checking for storage and adapters");e.cache.storage.controller(function(b){c.storage=b;a(b)},b);return c}};e.ns(l+".controller",
b)})(window.getNs());
(function(e,u,g){function c(a){t("[cache interface] "+a)}function b(a){this.storage=this.controller=null;this.params=a;this.queue=new m;this.timeout=this.interval=this.calls=0}function l(a){var c=null,e=p.length,d;a||(a=x);if(q)for(d=0;d<e;d+=1)h(p[d].params)===h(a)&&(c=p[d]);c||(c=new b(a),p.push(c));return c}function s(b,d,h){var g=l(b),m,p,q,r=function(){m=g.interval;e.clearInterval(m);m=e.setInterval(function(){g.timeout=p=g.timeout+a;q=g.storage;g.controller&&(q&&(q.adapter||!q.isEnabled))&&
(e.clearInterval(m),g.queue.flush());p>k&&(e.clearInterval(m),c("Timeout reached while waiting for cache controller!!!"),h())},a)};g?g.storage?d(g):(g.queue.add(function(){d(g)}),g.calls+=1,1===g.calls?g.controller=new u.cache.controller(function(a){g.storage=a;g.controller?g.queue.flush():r()},b):r()):(c("Whether finding nor initializing a cache interface is possible!!!"),h())}var p=[];g=u.helpers;var m=g.queue;g=g.utils;var t=g.log,r=g.isArray,q=g.getJson(),h=g.jsonToString,d=g.callback,a=15,k=
5E3,x={};g=function(){return{load:function(a,b,e){b=d(b);s(e,function(c){r(a)?c.controller.load(a,b):"applicationCache"===a?(c=c.storage)&&c.appCacheAdapter?c.appCacheAdapter.open(b,e):b(!1):b(!1)},function(){c("Get interface failed!");b(!1)});return this},remove:function(a,b,e){b=d(b);s(e,function(c){r(a)?c.controller.remove(a,b):b(!1)},function(){c("Get interface failed!");b(!1)});return this},setup:function(a){a&&(x=a);return this}}}();u.ns("cache.load",g.load);u.ns("cache.remove",g.remove);u.ns("cache.setup",
g.setup)})(window,window.getNs());
