(function(c,r){function d(){c[b]||(c[b]={});return c[b]}var b="app",a;a=d();a.namespace=a.ns=function(a,g){if(a){a=String(a);var m=a.split("."),s=m.length,p=c[b],q;p||(c[b]={});if(!m)return!1;for(q=0;q<s;q+=1)p[m[q]]||(p[m[q]]={}),q===s-1&&g!==r&&(p[m[q]]=g),p=p[m[q]];return p}return!1};c[b]=a;c.getNamespace=c.getNs=d})(window);
(function(c,r){function d(){if(!(this instanceof d))return new d;this.m=[];this.r=null;this.f=!1}d.prototype=d.fn={add:function(b){this.f?b(this.r):this.m.push(b)},flush:function(b){if(!this.f)for(this.r=b,this.f=!0;this.m[0];)this.m.shift()(b)}};c.ns("helpers.queue",d)})(window.getNs());
(function(c,r,d,b){var a=function(){var c=[];return{isString:function(a){return"string"===typeof a||a instanceof String},isFunction:function(g){a.isFunction=Object.prototype&&Object.prototype.toString?function(a){return"[object Function]"===Object.prototype.toString.call(a)}:function(a){return"function"===typeof a||a instanceof Function};return a.isFunction(g)},isArray:function(g){var b=Array.isArray,c=Object.prototype.toString;a.isFunction(b)?a.isArray=function(a){return b(a)}:a.isFunction(c)?a.isArray=
function(a){return"[object Array]"===c.call(a)}:a.isArray=function(b){return!!b&&a.isFunction(b.sort)};return a.isArray(g)},inArray:function(b,m,s){a.inArray=Array.prototype&&Array.prototype.indexOf?function(a,b,g){return c.indexOf.call(b,a,g)}:function(a,b,g){var l=b.length,t=0;if(g)return b[g]&&b[g]===a?g:-1;for(t=0;t<l;t+=1)if(b[t]===a)return t;return-1};return a.inArray(b,m,s)},callback:function(g){a.isFunction(g)||(g=function(){return b});return g},url:function(b){if(a.isString(b)){var c=r.createElement("a"),
n;c.href=b;n=c.pathname.match(/\/([^\/?#]+)$/i);return{source:b,protocol:c.protocol,host:c.hostname,port:c.port,query:c.search,file:n?n[1]:"/",hash:c.hash,path:c.pathname.replace(/^([^\/])/,"/$1"),extension:function(a){a=a.split(".");return a.length?a[a.length-1]:!1}(b),folder:function(){var a=b.lastIndexOf("/");return b.substr(0,a+1)}()}}},trim:function(b){if(!a.isString(b))return b;a.isFunction(String.prototype.trim)||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});return b.trim()}}}();
d.ns("helpers.utils",a)})(window,document,window.getNs());
(function(c,r,d,b){var a=function(){var n=c.console!==b,g=n?c.console:null,m=n&&g.log!==b,s=n&&g.warn!==b,p=n&&g.error!==b,q=n&&g.time!==b&&g.timeEnd!==b;return{logToScreen:function(a){var l=r.getElementById("log"),b=r.createElement("p");a=r.createTextNode(a);l&&(b.appendChild(a),l.appendChild(b))},log:function(){var b=Array.prototype.slice.call(arguments);b.length&&(m&&(g.log.apply?g.log.apply(g,b):g.log(b)),b=b[0],a.logToScreen(b))},warn:function(){var b=Array.prototype.slice.call(arguments),l;
b.length&&(l=b[0],s?g.warn.apply(g,b):a.log(l),a.logToScreen(l))},error:function(){var b=Array.prototype.slice.call(arguments),l;b.length&&(l=b[0],p?g.error.apply(g,b):a.log(l),a.logToScreen(l))},save:function(){n&&(c.Blob&&c.JSON&&c.URL)&&(g.save=function(a,l){if(!a&&p)g.error("Console.save: No data");else{l||(l="console.json");"object"===typeof a&&(a=JSON.stringify(a,b,4));var t=new Blob([a],{type:"text/json"}),f=r.createEvent("MouseEvents"),e=r.createElement("a");e.download=l;e.href=c.URL.createObjectURL(t);
e.dataset.downloadurl=["text/json",e.download,e.href].join(":");f.initMouseEvent("click",!0,!1,c,0,0,0,0,0,!1,!1,!1,!1,0,null);e.dispatchEvent(f)}})},logTimerStart:function(a){q&&g.time(a)},logTimerEnd:function(a){q&&g.timeEnd(a)}}}();d.namespace("helpers.console",a)})(window,document,window.getNs());
(function(c,r,d){var b=function(){var a=r.helpers.utils;return{getXhr:function(){for(var a=null,b=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],c=b.length,s=0,s=0;s<c;s+=1){try{a=b[s]()}catch(p){continue}break}return a},xhr:function(c,g,m,s){var p=b.getXhr(),q,r="GET";g=a.callback(g);if(p)if(c){s!==d?r="POST":s=null;m===d&&(m=!0);q=function(){if(4===
p.readyState&&(200<=p.status&&400>p.status||0===p.status))try{var a=p.responseText;a?g(a):g(!1)}catch(f){g(!1)}else 4===p.readyState&&g(!1)};p.open(r,c,m);try{p.onreadystatechange!==d?p.onreadystatechange=q:p.onload!==d&&(p.onload=q)}catch(l){}p.send(s)}else g(!1);else g(!1)}}}();r.namespace("helpers.ajax",b)})(window,window.getNs());
(function(c,r,d,b){var a=function(){return{on:function(b,g,m){a.on="function"===typeof c.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:"function"===typeof r.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a.on(b,g,m)},off:function(b,g,m){a.off="function"===typeof c.removeEventListener?function(a,b,c){a.removeEventListener(b,c,!1)}:"function"===typeof r.detachEvent?function(a,b,c){a.detachEvent("on"+b,c)}:function(a,b){a["on"+b]=null};a.off(b,g,m)}}}();
d.namespace("helpers.events",a)})(window,document,window.getNs());(function(c,r,d,b){var a=function(){var n=null,g=c.JSON;return{getJson:function(){null===n&&g&&g.stringify&&(n=g);return n},jsonToString:function(c,g,p){var d=!1;null===n&&(n=a.getJson());n&&(n.stringify&&c!==b)&&(d=n.stringify(c,g,p));return d},jsonToObject:function(c,g){var d=!1;null===n&&(n=a.getJson());n&&(n.parse&&c!==b)&&(d=n.parse(String(c),g));return d}}}();d.namespace("helpers.json",a)})(window,document,window.getNs());
(function(c,r,d,b){var a=function(){function a(){p===b&&(l(c,"online",a),l(c,"offline",a));p=r.onLine!==b?!!r.onLine:!0}var g,m,s,p,q,v=(r.userAgent||r.vendor||c.opera).toLowerCase(),l=d.helpers.events.on;return{isWebkit:function(){g===b&&(g=null!==v.match(/(webkit)/));return g},isMsie:function(){s===b&&(s=null!==v.match(/(msie)/));return s},isOpera:function(){m===b&&(m=null!==v.match(/(opera)/));return m},isOnline:function(){p===b&&a();return p},hasCanvas:function(){if(q===b){var a=document.createElement("canvas");
q=!(!a.getContext||!a.getContext("2d"))}return q}}}();d.ns("helpers.client",a)})(window,window.navigator,window.getNs());
(function(c,r,d){function b(a,b){b&&(b.dom?a=b.dom:b.id&&(a=c.getElementById(b.id)));return a}var a=function(){var n=r.helpers,g=n.utils,m=n.client,s=[],p=[],q=[],v=[],l=c.getElementsByTagName("head")[0];return{nuke:function(){s=[];p=[];q=[];v=[]},createDomNode:function(a,f){var e=c.createElement(a),b;if(f)for(b in f)f.hasOwnProperty(b)&&e.setAttribute(b,f[b]);return e},getAttribute:function(a,b){return a.getAttribute(b)},setAttribute:function(a,b,e){a.setAttribute(b,e)},appendCss:function(t,f,e,
h,k){if(-1===g.inArray(t,s)||k){var u=null,x=!1,w,d,u=b(u,h);if(null!==f){u||(u=a.createDomNode("style",{type:"text/css"}),u.className="lazyloaded");u.onerror=function(){e(!1)};h||l.appendChild(u);try{w=c.createTextNode(f),u.appendChild(w)}catch(y){u.styleSheet.cssText=f}finally{e(!0)}}else null!==t&&(u||(u=a.createDomNode("link",{rel:"stylesheet",type:"text/css"}),u.className="lazyloaded"),u.onerror=u.error=function(){u.onload=u.load=null;x=!0;window.clearTimeout(d);e(!1)},h||l.appendChild(u),m.isMsie()||
m.isOpera()?u.onload=u.load=function(){u.onerror=u.error=null;x=!0;window.clearTimeout(d);e(!0)}:e(!0),u.href=t,d=window.setTimeout(function(){x||e(!1)},4E3));s.push(t)}else e(!0)},appendJs:function(t,f,e,h,k){if(-1===g.inArray(t,p)||k){k=a.createDomNode("script");var u=c.getElementsByTagName("script")[0],x=!1,w=!1,d;(k=b(k,h))?(k.type="text/javascript",k.className="lazyloaded",k.async=!0,k.onreadystatechange=k.onload=function(){w||this.readyState&&"complete"!==this.readyState&&"loaded"!==this.readyState||
(this.onreadystatechange=this.onload=null,x=w=!0,window.clearTimeout(d),p.push(t),e(!0))},k.onerror=function(){this.onload=this.onreadystatechange=this.onerror=null;window.clearTimeout(d);x=!0;e(!1)},h||(u?u.parentNode.insertBefore(k,u):l.appendChild(k)),f&&!w?(k.textContent?k.textContent=f:k.nodeValue?k.nodeValue=f:k.text=f,x=w=!0):null!==t&&(k.src=t),w&&(p.push(t),x=!0,e(!0)),x||(d=window.setTimeout(function(){w||e(!1)},5E3))):e(!1)}else e(!0)},appendImg:function(a,f,e,h){var k=null;(k=b(k,h))||
(k=new Image);k.onerror=function(){k.onload=k.onerror=null;e(!1)};k.onload=function(){k.onload=k.onerror=null;e(!0)};f?k.src=f:a&&(k.src=a);if(k.complete&&k.naturalWidth!==d)k.onload();q.push(a)},appendHtml:function(a,f,e,h){var k=b(null,h);if(k){if(f)try{k.innerHTML=f,h.id&&m.isMsie()&&c.styleSheets[0].addRule("#"+h.id+":after",'content: " ";')}catch(l){k.innerText=f}e(!0);v.push(a)}else e(!1)}}}();r.ns("helpers.dom",a)})(document,window.getNs());
(function(c,r,d){function b(a){q("["+s+" Adapter] "+a)}function a(a){if(a){var e=a.name||a.code,h=a.message||a.description||"",k=h;if(FileError)switch(e){case FileError.ENCODING_ERR:case "EncodingError":k="Error Event: ENCODING_ERR "+h;break;case FileError.INVALID_MODIFICATION_ERR:case "InvalidModificationError":k="Error Event: INVALID_MODIFICATION_ERR";break;case FileError.INVALID_STATE_ERR:case "InvalidStateError":k="Error Event: INVALID_STATE_ERR "+h;break;case FileError.NO_MODIFICATION_ALLOWED_ERR:case "NoModificationAllowedError":k=
"Error Event: NO_MODIFICATION_ALLOWED_ERR "+h;break;case FileError.NOT_FOUND_ERR:case "NotFoundError":k="Error Event: NOT_FOUND_ERR "+h;break;case FileError.NOT_READABLE_ERR:case "NotReadableError":k="Error Event: NOT_READABLE_ERR "+h;break;case FileError.PATH_EXISTS_ERR:case "PathExistsError":k="Error Event: PATH_EXISTS_ERR "+h;break;case FileError.QUOTA_EXCEEDED_ERR:case "QuotaExceededError":k="Error Event: QUOTA_EXCEEDED_ERR "+h;break;case FileError.SECURITY_ERR:case "SecurityError":k="Error Event: SECURITY_ERR "+
h;break;case FileError.TYPE_MISMATCH_ERR:case "TypeMismatchError":k="Error Event: TYPE_MISMATCH_ERR "+h;break;default:k="Error Event: Unknown Error "+h}else k="Error Event: Unknown Error, no FileError available";b(k,a)}}function n(b,e,h){var k=function(b){a(b);h(!1)};if("."===e[0]||""===e[0])e=e.slice(1);e[0]?b.getDirectory(e[0],{create:!0},function(a){e.length?n(a,e.slice(1),h):h(!0)},k):h(!0)}function g(a,b,h){b=b.split("/");var k=b.length,l="",c=0;h=v(h);if(k){for(c=0;c<k-1;c+=1)l=l+b[c]+"/";n(a.root,
l.split("/"),h)}else h(!0)}function m(a){if(!(this instanceof m))return new m(a);this.adapter=null;this.type=s;this.size=52428800;this.init(a)}var s="fileSystem";d=r.helpers;var p=d.json,q=d.console.log,v=d.utils.callback,l=null,t=c.requestFileSystem||c.webkitRequestFileSystem||c.moz_requestFileSystem;m.prototype=m.fn={isSupported:function(){null===l&&((l=!!t&&(!!c.Blob||!!c.BlobBuilder)&&c.FileReader)||b(s+" is not supported"));return l},open:function(f){var e=this,h=e.adapter,k=function(b){a(b);
f(!1)};f=v(f);l?null===h?(c.requestFileSystem=t,c.requestFileSystem(c.TEMPORARY,e.size,function(a){h=e.adapter=a;b("Try to create test resource");try{e.create("test-item",p.jsonToString({test:"test-content"}),function(a){a?e.remove("test-item",function(){b("Test resource created and successfully deleted");f(h)}):k()})}catch(l){k(l)}},k)):(b("Adapter already opened"),f(h)):f(!1)},create:function(f,e,h){h=v(h);if(f&&l){var k=this.adapter,c=function(b){a(b);h(!1,b)};g(k,f,function(){k.root.getFile(f,
{create:!0},function(a){a.createWriter(function(a){var l;a.onwriteend=function(){b("File successfully written: url "+f);h(!0)};a.onerror=c;try{Blob?(l=new Blob([e],{type:"text/plain"}),a.write(l)):BlobBuilder&&(l=new BlobBuilder,l.append(e),a.write(l.getBlob("application/json")))}catch(k){c(k)}},c)},c)})}else h(!1)},read:function(b,e){e=v(e);if(b&&l){var h=this.adapter,k=function(b){a(b);e(!1,b)};g(h,b,function(){h.root.getFile(b,{create:!1},function(a){a.file(function(a){var b=new FileReader;b.onloadend=
function(){e(this.result)};b.onerror=k;b.onabort=k;b.readAsText(a)},k)},k)})}else e(!1)},update:function(a,b,h){this.create(a,b,h)},remove:function(b,e){e=v(e);if(b&&l){var h=this.adapter,k=function(b){a(b);e(!1,b)};g(h,b,function(){h.root.getFile(b,{create:!1},function(a){a.remove(function(){e(!0)},k)},k)})}else e(!1)},init:function(a){return this.isSupported()?(a&&a.size&&(this.size=a.size),this):!1}};r.ns("cache.storage.adapter."+s,m)})(window,window.getNs());
(function(c,r,d){function b(a){s("["+g+" Adapter] "+a)}function a(a){a&&b("Database error: "+(a.message||" No message avaible"))}function n(a){if(!(this instanceof n))return new n(a);this.adapter=null;this.type=g;this.dbName="cache";this.dbVersion="1.0";this.dbTable="offline";this.dbDescription="offline cache";this.dbKey="key";this.init(a)}var g="indexedDatabase",m=r.helpers,s=m.console.log,p=m.utils.callback,q=null,v=c.indexedDB||c.webkitIndexedDB||c.mozIndexedDB||c.OIndexedDB||c.msIndexedDB;n.prototype=
n.fn={isSupported:function(){null===q&&((q=!!v)||b(g+" is not supported"));return q},create:function(l,c,f){f=p(f);if(l&&q){var e=this.dbTable,h=this.dbName,k=this.adapter.transaction([e],"readwrite");l=k.objectStore(e).put({key:l,content:c});k.onerror=function(e){b("Failed to init transaction while creating/updating database entry "+h+" "+e);a(e);f(!1,e)};l.onerror=function(e){b("Failed to create/update database entry "+h+" "+e);a(e);f(!1,e)};l.onsuccess=function(){f(!0)}}else f(!1)},read:function(l,
c){c=p(c);if(l&&q){var f=this.dbTable,e=this.dbName,h=this.adapter.transaction([f],"readonly"),f=h.objectStore(f).get(l);h&&f?(h.onerror=function(h){b("Failed to init transaction while reading database "+e+" "+h);a(h);c(!1,h)},f.onerror=function(h){b("Failed to read database entry "+e+" "+h);a(h);c(!1,h)},f.onsuccess=function(a){a.target.result&&a.target.result.content?c(a.target.result.content):c(!1)}):c(!1)}else c(!1)},update:function(a,b,f){this.create(a,b,f)},remove:function(l,c){c=p(c);if(l&&
q){var f=this.dbTable,e=this.dbName,h=this.adapter.transaction([f],"readwrite"),f=h.objectStore(f).put({key:l,content:""});h.onerror=function(h){b("Failed to init transaction while deleting database entry "+e+" "+h);a(h);c(!1,h)};f.onerror=function(h){b("Failed to delete database entry "+e+" "+h);a(h);c(!1,h)};f.onsuccess=function(){c(!0)}}else c(!1)},open:function(l,g){g||(g=!1);l=p(l);var f=this,e=null,h=null,k=null,u=f.dbName,x=f.dbTable,n=function(a){a||l(!1);b("Try to create test resource");
f.create("test-item",'{test: "test-content"}',function(e){e?f.remove("test-item",function(){b("Test resource created and successfully deleted");l(a)}):l(!1)})},m,y,E,q,r;if(null===f.adapter)if(e=v){c.webkitIndexedDB!==d&&(c.IDBTransaction=c.webkitIDBTransaction,c.IDBKeyRange=c.webkitIDBKeyRange);m=function(a){a.createIndex(f.dbKey,f.dbKey,{unique:!0});a.createIndex("content","content",{unique:!1})};y=function(e){var c=h.result,g,t;f.adapter=c;b("Database request successfully done");f.dbVersion===
c.version||!c.setVersion&&"function"!==typeof c.setVersion?(f.adapter=c,n(c)):(k=e.currentTarget.result.setVersion(f.dbVersion),k.onfailure=function(e){b("Failed to open database: "+u+" "+e);a(e);l(!1)},k.onsuccess=function(e){g=h.result;try{t=g.createObjectStore(x,{keyPath:f.dbKey}),b("Database needs upgrade: "+u+" "+e.oldVersion+" "+e.newVersion),m(t)}catch(c){b("Failed to open database: "+u+" "+c),a(c),l(!1)}})};E=function(a){var e=h.result.createObjectStore(x,{keyPath:f.dbKey});b("Database needs upgrade: "+
u+" "+a.oldVersion+" "+a.newVersion);m(e)};q=function(e){b("Failed to open database: "+u+" "+e);a(e);g||f.open(l,!0);l(!1)};r=function(e){b("Opening database request is blocked! "+u+" "+e);a(e);l(!1)};if(g)try{h=e.open(u,f.dbVersion)}catch(s){b("Could not set version"),a(s),h=e.open(u)}else h=e.open(u);h.onsuccess=y;h.onupgradeneeded=E;h.onerror=q;h.onblocked=r}else l(!1);else n(f.adapter)},init:function(a){return this.isSupported()?(a&&(a.name&&(this.dbName=String(a.name)),a.version&&(this.dbVersion=
parseInt(a.version,10)),a.table&&(this.dbTable=a.table),a.description&&(this.dbDescription=String(a.description)),a.key&&(this.dbKey=a.key)),this):!1}};r.ns("cache.storage.adapter."+g,n)})(window,window.getNs());
(function(c,r,d){function b(a){s("["+m+" Adapter] "+a)}function a(a,b,c,e,h,k){!k&&a?a.transaction(function(a){a.executeSql(b,c,e,h)}):k?k.executeSql(b,c,e,h):h(null,{code:0,message:m+" isn't available"})}function n(a){var c="Errorcode: "+(a.code||"Code not present")+", Message: "+(a.message||"Message not present");a.info&&(c=c+" - "+a.info);b(c)}function g(a){if(!(this instanceof g))return new g(a);this.adapter=null;this.type=m;this.dbName="cache";this.dbVersion="1.0";this.dbDescription="resource cache";
this.dbTable="websql";this.dbSize=4194304;this.init(a)}var m="webSqlDatabase";d=r.helpers;var s=d.console.log,p=d.utils.callback,q=null,v=c.openDatabase;g.prototype=g.fn={isSupported:function(){null===q&&((q=!!v)||b(m+" is not supported"));return q},create:function(b,c,f){f=p(f);b&&q?a(this.adapter,"INSERT INTO "+this.dbTable+" (key, content) VALUES (?,?);",[b,c],function(){f(!0)},function(a,b){n(b);f(!1,b,{transaction:a})}):f(!1)},read:function(b,c){c=p(c);b&&q?a(this.adapter,"SELECT content FROM "+
this.dbTable+" WHERE key=?;",[b],function(a,b){var h=!1;b&&(b.rows&&1===b.rows.length)&&(h=b.rows.item(0).content);c(h,null,{transaction:a})},function(a,b){n(b);c(!1,b,{transaction:a})}):c(!1)},update:function(b,c,f){f=p(f);b&&q?a(this.adapter,"UPDATE "+this.dbTable+" SET content = ?  WHERE key=?;",[c,b],function(){f(!0)},function(a,b){n(b);f(!1,b,{transaction:a})}):f(!1)},remove:function(b,c){c=p(c);b&&q?a(this.adapter,"DELETE FROM "+this.dbTable+" WHERE key = ?;",[b],function(){c(!0)},function(a,
b){n(b);c(!1,b,{transaction:a})}):c(!1)},open:function(g){g=p(g);if(q){var d=this,f=d.adapter,e,h=function(a){a||g(!1);b("Try to create test resource");e=function(e){e?d.remove("test-item",function(){b("Test resource created and successfully deleted");g(a)}):g(!1)};d.read("test-item",function(a){a?d.update("test-item",'{test: "test-content"}',e):d.create("test-item",'{test: "test-content"}',e)})},k=function(e,c){b("Checking database table: name "+d.dbTable);a(e,"CREATE TABLE IF NOT EXISTS "+d.dbTable+
"(id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, key TEXT NOT NULL UNIQUE, content TEXT NOT NULL);",[],function(){h(d.adapter)},function(a){n(a);h(!1)},c)},u=function(a){k(null,a)},x=function(a){a.info="Can't migrate to new database version. This may be caused by non-standard implementation of the changeVersion method. Please switch back your database version to use webSql on this device.";n(a);g(!1)};try{if(null===f&&d.isSupported())if(b("Initializing database"),d.adapter=f=v(d.dbName,"",d.dbDescription,
d.dbSize),String(f.version)!==String(d.dbVersion)&&f.changeVersion&&"function"===typeof f.changeVersion){b("Try to update version: new version "+f.version+", old version "+d.dbVersion);try{f.changeVersion(f.version,d.dbVersion,u,x)}catch(m){n(m),g(!1)}}else b("Open database with version number: "+d.dbVersion),f=c.openDatabase(d.dbName,d.dbVersion,d.dbDescription,d.dbSize),k(f);else d.isSupported()&&(b("database already initialized"),h(f))}catch(r){n(r),g(!1)}}else g(!1)},init:function(a){return this.isSupported()?
(a&&(a.description&&(this.dbDescription=a.description),a.name&&(this.dbName=a.name),a.size&&(this.dbSize=a.size),a.table&&(this.dbTable=a.table),a.version&&(this.dbVersion=String(a.version))),this):!1}};r.ns("cache.storage.adapter."+m,g)})(window,window.getNs());
(function(c,r,d){function b(a){v("["+m+" Adapter] "+a)}function a(a){!a&&c.event&&(a=c.event);b("Event - key: "+(a.key||"no e.key event")+", url: "+(a.url||"no e.url event"))}function n(a){a=l(a);switch(a){case "local":a="localStorage";break;case "session":a="sessionStorage";break;default:a="localStorage"}return a}function g(a){if(!(this instanceof g))return new g(a);this.adapter=null;this.type=m;this.lifetime="local";this.asynch=!0;this.init(a)}var m="webStorage",s=r.helpers,p=s.utils,q=s.events.on,
v=s.console.log,l=p.trim,t=p.callback,f=null;g.prototype=g.fn={isSupported:function(){var a=n(this.lifetime);if(null===f)try{f=!!c[a]&&!!c[a].getItem}catch(h){b(m+" is not supported",h),f=!1}return f},create:function(b,c,f){var g=this,d=!0,l=function(a){if(g.asynch)f(a);else return a};f=t(f);if(!b)return l(!1);try{g.adapter.setItem(b,c)}catch(n){d=!d,a(n)}return l(d)},read:function(b,c){var f=this,g,d=!0,l=function(a){if(f.asynch)c(a);else return a};c=t(c);if(!b)return l(!1);try{d=(g=f.adapter.getItem(b))?
g:!1}catch(n){d=!d,a(n)}return l(d)},update:function(a,b,c){if(this.asynch)this.create(a,b,c);else return this.create(a,b,c)},remove:function(b,c){var f=this,g=!0,d=function(a){if(f.asynch)c(a);else return a};c=t(c);if(!b)return d(!1);try{f.adapter.removeItem(b)}catch(l){g=!g,a(l)}return d(g)},open:function(e){var h=this,f=h.adapter,g=n(h.lifetime),d,l,m=function(a){if(h.asynch)e(a);else return a};e=t(e);if(null===f)try{if(f=h.adapter=c[g],q(c,"storage",a),b("Lifetime used: "+g),b("Try to create test resource"),
h.asynch)h.create("test-item",'{test: "test-content"}',function(a){a?h.remove("test-item",function(){b("Test resource created and successfully deleted");e(f)}):e(!1)});else{if(d=h.create("test-item",'{test: "test-content"}'))if(l=h.remove("test-item"))return b("Test resource created and successfully deleted"),f;return!1}}catch(p){return a(p),m(!1)}else if(h.isSupported())return m(f)},init:function(a){return this.isSupported()?(a&&(a.lifetime&&(this.lifetime=l(String(a.lifetime))),a.asynch!==d&&(this.asynch=
!!a.asynch)),this):!1}};r.ns("cache.storage.adapter."+m,g)})(window,window.getNs());
(function(c,r,d,b){function a(a){v("["+m+" Adapter] "+a)}function n(b,f){f.isLoaded||(f.isLoaded=!0,f.progressCallback(100),c.setTimeout(function(){b();a("Event loaded")},f.delay))}function g(a){if(!(this instanceof g))return new g(a);this.adapter=null;this.type=m;this.isLoaded=!1;this.delay=0;this.opened=!0;this.message="New version available. Update page?";this.init(a)}var m="applicationCache",s=d.helpers,p=s.dom,q=s.events.on,v=s.console.log,l=s.utils.callback,t=null,f=r.getElementsByTagName("html")[0],
e=c.applicationCache;g.prototype=g.fn={isSupported:function(){null===t&&((t=!!e&&!!p.getAttribute(f,"manifest"))||a(m+" is not supported or there is no manifest html attribute"));return t},open:function(f,e){var g=this,d=g.adapter,m=0,p,r;g.opened=!0;f=l(f);e&&e.progress&&(p=e.progress);p=g.progressCallback=l(p);if(g.isSupported()&&null!==d){r=function(){a("Event updateready");try{d.swapCache()}catch(b){a("Event updateready: swapcache is not available",b)}confirm(g.message)?c.location.reload(!0):
n(f,g);return!1};q(d,"checking",function(){a("Event checking");return!1});q(d,"noupdate",function(){a("Event noupdate");n(f,g);return!1});q(d,"downloading",function(){a("Event downloading");m=0;return!1});q(d,"progress",function(c){a("Event progress");var f=0;g.delay=500;m+=1;f=c&&c.lengthComputable!==b?Math.round(100*c.loaded/c.total):Math.round(100*m/20);p(f);return!1});q(d,"cached",function(){a("Event cached");n(f,g);return!1});q(d,"updateready",function(){r()});q(d,"obsolete",function(){a("Event obsolete");
c.location.reload(!0);return!1});q(d,"error",function(){a("Event error");n(f,g);return!1});switch(d.status){case d.UNCACHED:n(f,g);break;case d.IDLE:n(f,g);break;case d.UPDATEREADY:r();break;case d.OBSOLETE:n(f,g)}q(c,"online",function(){try{d.update()}catch(b){a("Window event online: update cache is not available",b)}});c.setTimeout(function(){g.isLoaded||n(f,g)},12E3)}else n(f,g)},init:function(a){this.isSupported()&&(null===this.adapter&&(this.adapter=e),a&&(a.message&&(this.message=String(a.message)),
a.delay!==b&&(this.delay=parseInt(a.delay,10))));return this}};d.ns("cache.storage.adapter."+m,g)})(window,document,window.getNs());
(function(c,r,d,b){function a(a){E("["+h+" controller] "+a)}function n(b){var c="";b&&(c="Error Event: Description "+(b.description||"no description available"));a(c)}function g(a,b,f){f.timeoutXhr=c.setTimeout(function(){b(!1)},4E3);L(a,function(a){c.clearTimeout(f.timeoutXhr);delete f.timeoutXhr;a?b(a):b(!1)})}function m(b){var c=null;try{c=w.jsonToObject(b)}catch(f){n(f),a("Couldn't convert json string to object.")}return c}function s(a,c,f){if(J){var e=r.createElement("canvas"),g,d=new Image,
h=null,k=0,l=0;f||(f="jpeg");d.onerror=function(){d.onload=d.onerror=null;c()};d.onload=function(){d.onload=d.onerror=null;k=e.height=d.height;l=e.width=d.width;g=e.getContext("2d");g.fillStyle="rgba(50, 50, 50, 0)";g.fillRect(0,0,l,k);g.drawImage(d,0,0);h=e.toDataURL("image/"+f);c(h)};I&&(d.src="");d.src=a;if(d.complete&&d.naturalWidth!==b)d.onload()}else c(!1)}function p(a){var b=a.data,c=a.url;"css"===a.type&&(c=x.url(c),c=c.folder,b=b.replace(/url\(\../g,"url("+c+".."),b=b.replace(/url\(\'../g,
"url('"+c+".."),b=b.replace(/url\(\"../g,'url("'+c+".."),a.data=b);return a}function q(a,c){return{ajax:a.ajax,data:a.data,expires:(new Date).getTime()+(a.lifetime||c.lifetime),group:a.group!==b?a.group:c.group,lastmod:a.lastmod||c.lastmod,lifetime:a.lifetime!==b?a.lifetime:c.lifetime,type:a.type||c.type,version:a.version||c.version}}function v(a,b,c){var f=a.type,e=a.url,d=a.data;a.ajax?"img"===f?s(e,b):g(e,b,a):d?b(d):c(!1)}function l(a){return C&&C[a]?!!C[a]:!1}function t(b,c){var f=null,e,g;b&&
b.length?(e=b[0].type,g=b.slice(1),a("Testing for storage adapter type: "+e),A[e]?f=new A[e](F):t(g,c),f&&f.isSupported()?f.open(function(d){d?(D=e,C=b[0],a("Used storage adapter type: "+D),c(f)):t(g,c)}):t(g,c)):c(!1)}function f(b,c,e){var g=null,d=0,h;if(e)try{a("Testing for preferred storage adapter type: "+e),A[e]?(g=new A[e](F))&&g.isSupported()?g.open(function(k){if(k){D=e;h=c.length;for(d=0;d<h;d+=1)c[d].type===e&&(C=c[d]);C?(a("Used storage type: "+D),b(g)):(a("Storage config not found: "+
D),f(b,c))}else f(b,c)}):f(b,c):f(b,c)}catch(k){n(k),a("Storage adapter could not be initialized: type "+e),f(b,c)}else t(c,b)}function e(a,b){if(!(this instanceof e))return new e(a,b);this.isEnabled=!0;this.appCacheAdapter=this.adapter=null;this.adapters={types:K,defaults:F};this.resources={defaults:M};this.init(a,b)}var h="storage",k=d.helpers,u=k.client,x=k.utils,w=k.json,G=k.ajax,y=x.isArray,E=k.console.log,B=x.callback,H=w.getJson(),L=G.xhr,z=x.trim,A=d.cache.storage.adapter,I=u.isWebkit(),J=
u.hasCanvas(),K=[{type:"fileSystem",css:!0,js:!0,html:!0,img:!0},{type:"indexedDatabase",css:!0,js:!0,html:!0,img:!0},{type:"webSqlDatabase",css:!0,js:!0,html:!0,img:!0},{type:"webStorage",css:!0,js:!0,html:!0,img:!0}],F={name:"localcache",table:"cache",description:"local resource cache",size:4194304,version:"1.0",key:"key",lifetime:"local",offline:!0},D=null,C=null,M={ajax:!0,lifetime:2E4,group:0,lastmod:(new Date).getTime(),type:"css",version:1};e.prototype=e.fn={create:function(b,c){c=B(c);if(b&&
b.url){var f=this,e=b.url,g=b.type;v(b,function(d){if(d)if(b.data=d,b=p(b),null!==f.adapter&&l(g)){d=w.jsonToString(e);var h=q(b,f.resources.defaults),k=w.jsonToString(h);b.expires=h.expires;b.version=h.version;try{f.adapter.create(d,k,function(f){f?(a("Create new resource in storage adapter: type "+g+", url "+e),c(b)):(a("Create new resource in storage adapter failed"),c(!1))})}catch(m){n(m),a("Create new resource in storage adapter failed"),c(b)}}else a("Trying to create new resource, but resource type is not cachable or storage adapter is not available: type "+
g+", url "+e),c(b);else a("Couldn't get data via network"),c(b)},c)}else c(!1)},read:function(b,c){c=B(c);if(b&&b.url){var f=this,e=b.url,d=b.type;if(null!==this.adapter&&l(d)){a("Trying to read resource from storage: type "+d+", url "+e);try{f.adapter.read(w.jsonToString(e),function(g){g?(b=m(g))?(b.url=e,a("Successfully read resource from storage: type "+d+", url "+e),c(b,!0)):f.remove({url:e,type:d},function(){c(!1)}):(a("There is no data coming back from storage while reading: type "+d+", url "+
e),c(!1))})}catch(h){n(h),a("Try to read resource from storage, but storage adapter is not available: type "+d+", url "+e),g(e,function(f){a("Data loaded via ajax: type "+d+", url "+e+", data status "+!!f);b.data=f;c(b,!0)},b)}}else c(b)}else c(!1)},update:function(b,c){c=B(c);if(b&&b.url){var f=this,e=b.url,d=b.type;v(b,function(g){if(g)if(b.data=g,b=p(b),null!==f.adapter&&l(d)){g=w.jsonToString(e);var h=q(b,f.resources.defaults),k=w.jsonToString(h);b.expires=h.expires;b.version=h.version;try{f.adapter.update(g,
k,function(f){f?(a("Updated existing resource in storage adapter: type "+d+", url "+e),c(b)):(a("Updating resource in storage failed."),c(!1))})}catch(m){n(m),a("Updating resource in storage failed."),c(b)}}else a("Resource type is not cachable or storage adapter is not available: type "+d+", url "+e),c(b);else a("Couldn't get data via network, trying to used stored version"),f.read(b,function(a){a&&a.data?(b.data=a.data,c(b)):c(!1)})},c)}else c(!1)},remove:function(b,c){c=B(c);if(b&&b.url){var f=
b.url,e=b.type;null!==this.adapter&&l(e)?this.adapter.remove(w.jsonToString(f),function(d){d?(a("Delete resource form storage: type "+e+", url "+f),c(b)):(a("Deleting resource form storage failed: type "+e+", url "+f),c(!1))}):(a("Delete resource from storage failed, resource type is not cachable or there is no storage adapter: type "+e+", url "+f),c(b))}else c(!1)},init:function(c,e){var d=this,g=!1,h,k,l,m;c=B(c);e&&e.isEnabled!==b&&(d.isEnabled=!!e.isEnabled);if(d.isEnabled&&H){if(e){if(e.adapters){h=
e.adapters;if(h.types&&y(h.types)){k=h.types;l=k.length;for(m=0;m<l;m+=1)k[m].css===b&&(k[m].css=!0),k[m].js===b&&(k[m].js=!0),k[m].img===b&&(k[m].img=!0),k[m].html===b&&(k[m].html=!0);d.adapters.types=k}h.defaults&&(k=h.defaults,l=d.adapters.defaults,k.name&&(l.name=z(String(k.name))),k.table&&(l.table=z(String(k.table))),k.description&&(l.description=z(String(k.description))),k.size&&(l.size=parseInt(k.size,10)),k.version&&(l.version=z(String(k.version))),k.key&&(l.key=z(String(k.key))),k.lifetime&&
(l.lifetime=z(String(k.lifetime))),k.offline!==b&&(l.offline=!!k.offline));h.preferredType&&(g=z(String(h.preferredType)))}e.resources&&(h=e.resources,h.defaults&&(h=h.defaults,k=d.resources.defaults,h.ajax!==b&&(k.ajax=!!h.ajax),h.lifetime!==b&&(k.lifetime=parseInt(h.lifetime,10)),h.group!==b&&(k.group=parseInt(h.group,10)),h.lastmod!==b&&(k.lastmod=parseInt(h.lastmod,10)),h.type&&(k.type=z(String(h.type))),h.group!==b&&(k.version=parseFloat(h.version)),h.loaded&&(k.loaded=B(h.loaded))))}f(function(a){a||
(d.isEnabled=!1);d.adapter=a;c(d)},d.adapters.types,g);d.adapters.defaults.offline&&(A.applicationCache&&!d.appCacheAdapter)&&(d.appCacheAdapter=new A.applicationCache(F))}else H||a("There is no json support"),d.isEnabled||a("Caching data is disabled"),c(d)}};d.ns("cache."+h+".controller",e)})(window,document,window.getNs());
(function(c,r){function d(a){q("["+n+" controller] "+a)}function b(a){var b=l(a.type);if("js"!==b||"css"!==b||"html"!==b||"img"!==b||"custom"!==b){switch(s.url(a.url).extension){case "js":a="js";break;case "css":a="css";break;case "html":a="html";break;case "jpg":case "jpeg":case "png":a="img";break;default:a="custom"}b=a}return b}function a(b,c){if(!(this instanceof a))return new a(b,c);this.storage=null;this.init(b,c)}var n="cache",g=c.helpers,m=g.dom,s=g.utils,p=g.client,q=g.console.log,v=s.isArray,
l=s.trim,t=s.callback;a.prototype=a.fn={load:function(a,c){var g=this,k=(new Date).getTime(),n=function(){var a=0,b=0,c=null;return{init:function(f,e){c=e;a=f;b=0},loaded:function(){b+=1;b===a&&c()}}}(),q=function(a,b,c){var f=a.url,e=function(){a.loaded(a);n.loaded()},g=a.node||null;c=!!c;switch(a.type){case "js":m.appendJs(f,b,e,g,c);break;case "css":m.appendCss(f,b,e,g,c);break;case "img":m.appendImg(f,b,e,g,c);break;case "html":m.appendHtml(f,b,e,g,c);break;default:d("Didn't match any type for dom append: type "+
a.type),e()}},s=function(a){var b=a.data||null,c=function(a,b){a&&a.data?q(a,a.data,b):q(a,null,b)},f=g.storage,e=f.resources.defaults;a.ajax=a.ajax!==r?!!a.ajax:e.ajax;a.loaded=a.loaded!==r?t(a.loaded):t(e.loaded);f.read(a,function(e){if(e&&e.data){var l=a,m=g.storage.resources.defaults,n=parseInt(e.lifetime,10),s=e.version,u=e.lastmod?e.lastmod:0,y=!1,t,w=l.lastmod?l.lastmod:0,y=!0;t=!1;l.version=t=l.version!==r?parseFloat(l.version):m.version;l.group=l.group!==r?parseFloat(l.group):m.group;w&&
u?(l.lastmod=parseInt(w,10),y=u===l.lastmod):!w&&u?w=u:w||(w=m.lastmod);y=y&&t===s;t=0!==n&&(-1!==n&&y&&e.expires>k||-1===n&&y);l.lastmod=w;l.isValid=t;a=l;a.isValid||!p.isOnline()?(d("Resource is up to date: type "+a.type+", url "+a.url),(b=e.data)&&q(a,b)):(d("Resource is outdated and needs update: type "+a.type+", url "+a.url),f.update(a,c))}else d("Resource or resource data is not available in storage adapter, try to create it: type "+a.type+", url "+a.url),f.create(a,c)})},G=function(a,c){var e=
0,f=a.length,d=null;n.init(f,c);for(e=0;e<f;e+=1)(d=a[e])&&d.url&&(d.url=l(d.url),d.type=b(d),s(d))},y=function(a,b,c){var e=a.length;for(c||(c=0);!a[c]&&c<e;)c+=1;c>=e?b(g):(e=a[c],G(e,function(){y(a,b,c+1)}))};(function(a,b){var f;a&&v(a)||(a=[]);f=a.length;for(var g=a,h=[],k,l=0,m,n=g.length,l=0;l<n;l+=1)m=g[l],(k=m.group)||(k=0),k=h[k]?h[k]:h[k]=[],k.push(m);a=h;b=t(c);d("Load resource function called: "+f+" resources, "+a.length+" groups");y(a,b)})(a,c)},remove:function(a,c){var g=this.storage,
k=function(a,c){var e=a.length,f,k,m=function(a,b){d("Successfully removed resource: url "+b);a===e-1&&c()};if(e)for(f=0;f<e;f+=1)(k=a[f])&&k.url&&(k.url=l(k.url),k.type=b(k),g.remove(k,m(f,k.url)));else c()};(function(a,b){a&&v(a)||(a=[]);b=t(c);d("Remove resource function called: resources count "+a.length);k(a,b)})(a,c)},init:function(a,b){var g=this;a=t(a);d("Cache initializing, checking for storage and adapters");c.cache.storage.controller(function(b){g.storage=b;a(b)},b);return g}};c.ns(n+".controller",
a)})(window.getNs());
(function(c,r,d){function b(a){v("[cache interface] "+a)}function a(a){this.storage=this.controller=null;this.params=a;this.queue=new s;this.timeout=this.interval=this.calls=0}function n(b){var c=null,e=m.length,d;b||(b=u);if(t)for(d=0;d<e;d+=1)m[d]&&f(m[d].params)===f(b)&&(c=m[d]);c||(c=new a(b),m.push(c));return c}function g(a,e,f){var d=n(a),g,l,m,p=function(){g=d.interval;c.clearInterval(g);g=c.setInterval(function(){d.timeout=l=d.timeout+h;m=d.storage;d.controller&&(m&&(m.adapter||!m.isEnabled))&&
(c.clearInterval(g),d.queue.flush());l>k&&(c.clearInterval(g),b("Timeout reached while waiting for cache controller!!!"),f())},h)};d?d.storage?e(d):(d.queue.add(function(){e(d)}),d.calls+=1,1===d.calls?d.controller=new r.cache.controller(function(a){d.storage=a;d.controller?d.queue.flush():p()},a):p()):(b("Whether finding nor initializing a cache interface is possible!!!"),f())}var m=[];d=r.helpers;var s=d.queue,p=d.utils,q=d.json,v=d.console.log,l=p.isArray,t=q.getJson(),f=q.jsonToString,e=p.callback,
h=15,k=5E3,u={};d=function(){return{load:function(a,c,d){c=e(c);g(d,function(b){l(a)?b.controller.load(a,c):"applicationCache"===a?(b=b.storage)&&b.appCacheAdapter?b.appCacheAdapter.open(c,d):c(!1):c(!1)},function(){b("Get interface failed!");c(!1)});return this},remove:function(a,c,d){c=e(c);g(d,function(b){l(a)?b.controller.remove(a,c):c(!1)},function(){b("Get interface failed!");c(!1)});return this},setup:function(a){a&&(u=a);return this}}}();r.ns("cache.load",d.load);r.ns("cache.remove",d.remove);
r.ns("cache.setup",d.setup)})(window,window.getNs());
