(function(c,t){function n(){c[b]||(c[b]={});return c[b]}var b="app",a;a=n();a.namespace=a.ns=function(a,f){if(a){a=String(a);var p=a.split("."),s=p.length,r=c[b],q;r||(c[b]={});if(!p)return!1;for(q=0;q<s;q+=1)r[p[q]]||(r[p[q]]={}),q===s-1&&f!==t&&(r[p[q]]=f),r=r[p[q]];return r}return!1};c[b]=a;c.getNamespace=c.getNs=n})(window);
(function(c,t){function n(){if(!(this instanceof n))return new n;this.m=[];this.r=null;this.f=!1}n.prototype=n.fn={add:function(b){this.f?b(this.r):this.m.push(b)},flush:function(b){if(!this.f)for(this.r=b,this.f=!0;this.m[0];)this.m.shift()(b)}};c.ns("helpers.queue",n)})(window.getNs());
(function(c,t,n,b){var a=function(){var c=[];return{isString:function(a){return"string"===typeof a||a instanceof String},isFunction:function(a){return"function"===typeof a||a instanceof Function},isArray:function(b){var c=Array.isArray,l=Object.prototype.toString;a.isArray=c&&"function"===typeof c?function(a){return c(a)}:l&&"function"===l?function(a){return"[object Array]"===l.call(a)}:function(a){return!!a&&!!a.sort&&"function"===typeof a.sort};return a.isArray(b)},inArray:function(b,p,s){a.inArray=
Array.prototype.indexOf?function(a,b,f){return c.indexOf.call(b,a,f)}:function(a,b,f){var m=b.length,h=0;if(f)return b[f]&&b[f]===a?f:-1;for(h=0;h<m;h+=1)if(b[h]===a)return h;return-1};return a.inArray(b,p,s)},callback:function(f){a.isFunction(f)||(f=function(){return b});return f},url:function(b){if(a.isString(b)){var c=t.createElement("a"),l;c.href=b;l=c.pathname.match(/\/([^\/?#]+)$/i);return{source:b,protocol:c.protocol,host:c.hostname,port:c.port,query:c.search,file:l?l[1]:"/",hash:c.hash,path:c.pathname.replace(/^([^\/])/,
"/$1"),extension:function(a){a=a.split(".");return a.length?a[a.length-1]:!1}(b),folder:function(){var a=b.lastIndexOf("/");return b.substr(0,a+1)}()}}},trim:function(b){if(!a.isString(b))return b;a.isFunction(String.prototype.trim)||(String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")});return b.trim()}}}();n.ns("helpers.utils",a)})(window,document,window.getNs());
(function(c,t,n,b){var a=function(){var l=c.console!==b,f=l?c.console:null,p=l&&f.log!==b,s=l&&f.warn!==b,r=l&&f.error!==b,q=l&&f.time!==b&&f.timeEnd!==b;return{logToScreen:function(a){var m=t.getElementById("log"),h=t.createElement("p");a=t.createTextNode(a);m&&(h.appendChild(a),m.appendChild(h))},log:function(){var b=Array.prototype.slice.call(arguments);b.length&&(p&&(f.log.apply?f.log.apply(f,b):f.log(b)),b=b[0],a.logToScreen(b))},warn:function(){var b=Array.prototype.slice.call(arguments),m;
b.length&&(m=b[0],s?f.warn.apply(f,b):a.log(m),a.logToScreen(m))},error:function(){var b=Array.prototype.slice.call(arguments),m;b.length&&(m=b[0],r?f.error.apply(f,b):a.log(m),a.logToScreen(m))},save:function(){l&&(c.Blob&&c.JSON&&c.URL)&&(f.save=function(a,m){if(!a&&r)f.error("Console.save: No data");else{m||(m="console.json");"object"===typeof a&&(a=JSON.stringify(a,b,4));var h=new Blob([a],{type:"text/json"}),e=t.createEvent("MouseEvents"),d=t.createElement("a");d.download=m;d.href=c.URL.createObjectURL(h);
d.dataset.downloadurl=["text/json",d.download,d.href].join(":");e.initMouseEvent("click",!0,!1,c,0,0,0,0,0,!1,!1,!1,!1,0,null);d.dispatchEvent(e)}})},logTimerStart:function(a){q&&f.time(a)},logTimerEnd:function(a){q&&f.timeEnd(a)}}}();n.namespace("helpers.console",a)})(window,document,window.getNs());
(function(c,t,n){var b=function(){var a=t.helpers.utils;return{getXhr:function(){for(var a=null,b=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}],c=b.length,s=0,s=0;s<c;s+=1){try{a=b[s]()}catch(r){continue}break}return a},xhr:function(c,f,p,s){var r=b.getXhr(),q,t="GET";f=a.callback(f);if(r)if(c){s!==n?t="POST":s=null;p===n&&(p=!0);q=function(){if(4===
r.readyState&&(200<=r.status&&400>r.status||0===r.status))try{var a=r.responseText;a?f(a):f(!1)}catch(e){f(!1)}else 4===r.readyState&&f(!1)};r.open(t,c,p);try{r.onreadystatechange!==n?r.onreadystatechange=q:r.onload!==n&&(r.onload=q)}catch(m){}r.send(s)}else f(!1);else f(!1)}}}();t.namespace("helpers.ajax",b)})(window,window.getNs());
(function(c,t,n,b){var a=function(){return{on:function(b,f,p){a.on="function"===typeof c.addEventListener?function(a,b,c){a.addEventListener(b,c,!1)}:"function"===typeof t.attachEvent?function(a,b,c){a.attachEvent("on"+b,c)}:function(a,b,c){a["on"+b]=c};a.on(b,f,p)},off:function(b,f,p){a.off="function"===typeof c.removeEventListener?function(a,b,c){a.removeEventListener(b,c,!1)}:"function"===typeof t.detachEvent?function(a,b,c){a.detachEvent("on"+b,c)}:function(a,b){a["on"+b]=null};a.off(b,f,p)}}}();
n.namespace("helpers.events",a)})(window,document,window.getNs());(function(c,t,n,b){var a=function(){var l=null,f=c.JSON;return{getJson:function(){null===l&&f&&f.stringify&&(l=f);return l},jsonToString:function(c,f,n){var q=!1;null===l&&(l=a.getJson());l&&(l.stringify&&c!==b)&&(q=l.stringify(c,f,n));return q},jsonToObject:function(c,f){var n=!1;null===l&&(l=a.getJson());l&&(l.parse&&c!==b)&&(n=l.parse(String(c),f));return n}}}();n.namespace("helpers.json",a)})(window,document,window.getNs());
(function(c,t,n,b){var a=function(){function a(){s===b&&(v(c,"online",a),v(c,"offline",a));s=t.onLine!==b?!!t.onLine:!0}var f,p,s,r,q=(t.userAgent||t.vendor||c.opera).toLowerCase(),v=n.helpers.events.on;return{isMsie:function(){p===b&&(p=null!==q.match(/(msie)/));return p},isOpera:function(){f===b&&(f=null!==q.match(/(opera)/));return f},isOnline:function(){s===b&&a();return s},hasCanvas:function(){if(r===b){var a=document.createElement("canvas");r=!(!a.getContext||!a.getContext("2d"))}return r}}}();
n.ns("helpers.client",a)})(window,window.navigator,window.getNs());
(function(c,t,n){function b(a,b){b&&(b.dom?a=b.dom:b.id&&(a=c.getElementById(b.id)));return a}var a=function(){var l=t.helpers,f=l.utils,p=l.client,s=[],r=[],q=[],v=[],m=c.getElementsByTagName("head")[0];return{nuke:function(){s=[];r=[];q=[];v=[]},createDomNode:function(a,e){var d=c.createElement(a),b;if(e)for(b in e)e.hasOwnProperty(b)&&d.setAttribute(b,e[b]);return d},getAttribute:function(a,e){return a.getAttribute(e)},setAttribute:function(a,e,d){a.setAttribute(e,d)},appendCss:function(h,e,d,
k,g){if(-1===f.inArray(h,s)||g){var u=null,x=!1,w,l,u=b(u,k);if(null!==e){u||(u=a.createDomNode("style",{type:"text/css"}),u.className="lazyloaded");u.onerror=function(){d(!1)};k||m.appendChild(u);try{w=c.createTextNode(e),u.appendChild(w)}catch(y){u.styleSheet.cssText=e}finally{d(!0)}}else null!==h&&(u||(u=a.createDomNode("link",{rel:"stylesheet",type:"text/css"}),u.className="lazyloaded"),u.onerror=u.error=function(){u.onload=u.load=null;x=!0;window.clearTimeout(l);d(!1)},k||m.appendChild(u),p.isMsie()||
p.isOpera()?u.onload=u.load=function(){u.onerror=u.error=null;x=!0;window.clearTimeout(l);d(!0)}:d(!0),u.href=h,l=window.setTimeout(function(){x||d(!1)},4E3));s.push(h)}else d(!0)},appendJs:function(h,e,d,k,g){if(-1===f.inArray(h,r)||g){g=a.createDomNode("script");var u=c.getElementsByTagName("script")[0],x=!1,w=!1,l;(g=b(g,k))?(g.type="text/javascript",g.className="lazyloaded",g.async=!0,g.onreadystatechange=g.onload=function(){w||this.readyState&&"complete"!==this.readyState&&"loaded"!==this.readyState||
(this.onreadystatechange=this.onload=null,x=w=!0,window.clearTimeout(l),r.push(h),d(!0))},g.onerror=function(){this.onload=this.onreadystatechange=this.onerror=null;window.clearTimeout(l);x=!0;d(!1)},k||(u?u.parentNode.insertBefore(g,u):m.appendChild(g)),e&&!w?(g.textContent?g.textContent=e:g.nodeValue?g.nodeValue=e:g.text=e,x=w=!0):null!==h&&(g.src=h),w&&(r.push(h),x=!0,d(!0)),x||(l=window.setTimeout(function(){w||d(!1)},5E3))):d(!1)}else d(!0)},appendImg:function(a,e,d,k){var g=null;(g=b(g,k))||
(g=new Image);g.onerror=function(){g.onload=g.onerror=null;d(!1)};g.onload=function(){g.onload=g.onerror=null;d(!0)};e?g.src=e:a&&(g.src=a);if(g.complete&&g.naturalWidth!==n)g.onload();q.push(a)},appendHtml:function(a,e,d,k){var g=b(null,k);if(g){if(e)try{g.innerHTML=e,k.id&&p.isMsie()&&c.styleSheets[0].addRule("#"+k.id+":after",'content: " ";')}catch(m){g.innerText=e}d(!0);v.push(a)}else d(!1)}}}();t.ns("helpers.dom",a)})(document,window.getNs());
(function(c,t,n){function b(a){q("["+s+" Adapter] "+a)}function a(a){if(a){var d=a.name||a.code,k=a.message||a.description||"",g=k;if(FileError)switch(d){case FileError.ENCODING_ERR:case "EncodingError":g="Error Event: ENCODING_ERR "+k;break;case FileError.INVALID_MODIFICATION_ERR:case "InvalidModificationError":g="Error Event: INVALID_MODIFICATION_ERR";break;case FileError.INVALID_STATE_ERR:case "InvalidStateError":g="Error Event: INVALID_STATE_ERR "+k;break;case FileError.NO_MODIFICATION_ALLOWED_ERR:case "NoModificationAllowedError":g=
"Error Event: NO_MODIFICATION_ALLOWED_ERR "+k;break;case FileError.NOT_FOUND_ERR:case "NotFoundError":g="Error Event: NOT_FOUND_ERR "+k;break;case FileError.NOT_READABLE_ERR:case "NotReadableError":g="Error Event: NOT_READABLE_ERR "+k;break;case FileError.PATH_EXISTS_ERR:case "PathExistsError":g="Error Event: PATH_EXISTS_ERR "+k;break;case FileError.QUOTA_EXCEEDED_ERR:case "QuotaExceededError":g="Error Event: QUOTA_EXCEEDED_ERR "+k;break;case FileError.SECURITY_ERR:case "SecurityError":g="Error Event: SECURITY_ERR "+
k;break;case FileError.TYPE_MISMATCH_ERR:case "TypeMismatchError":g="Error Event: TYPE_MISMATCH_ERR "+k;break;default:g="Error Event: Unknown Error "+k}else g="Error Event: Unknown Error, no FileError available";b(g,a)}}function l(b,d,k){var g=function(d){a(d);k(!1)};if("."===d[0]||""===d[0])d=d.slice(1);d[0]?b.getDirectory(d[0],{create:!0},function(a){d.length?l(a,d.slice(1),k):k(!0)},g):k(!0)}function f(a,d,b){d=d.split("/");var g=d.length,m="",c=0;b=v(b);if(g){for(c=0;c<g-1;c+=1)m=m+d[c]+"/";l(a.root,
m.split("/"),b)}else b(!0)}function p(a){if(!(this instanceof p))return new p(a);this.adapter=null;this.type=s;this.size=52428800;this.init(a)}var s="fileSystem";n=t.helpers;var r=n.json,q=n.console.log,v=n.utils.callback,m=null,h=c.requestFileSystem||c.webkitRequestFileSystem||c.moz_requestFileSystem;p.prototype=p.fn={isSupported:function(){null===m&&((m=!!h&&(!!c.Blob||!!c.BlobBuilder)&&c.FileReader)||b(s+" is not supported"));return m},open:function(e){var d=this,k=d.adapter,g=function(d){a(d);
e(!1)};e=v(e);m?null===k?(c.requestFileSystem=h,c.requestFileSystem(c.TEMPORARY,d.size,function(a){k=d.adapter=a;b("Try to create test resource");try{d.create("test-item",r.jsonToString({test:"test-content"}),function(a){a?d.remove("test-item",function(){b("Test resource created and successfully deleted");e(k)}):g()})}catch(m){g(m)}},g)):(b("Adapter already opened"),e(k)):e(!1)},create:function(e,d,k){k=v(k);if(e&&m){var g=this.adapter,c=function(d){a(d);k(!1,d)};f(g,e,function(){g.root.getFile(e,
{create:!0},function(a){a.createWriter(function(a){var g;a.onwriteend=function(){b("File successfully written: url "+e);k(!0)};a.onerror=c;try{Blob?(g=new Blob([d],{type:"text/plain"}),a.write(g)):BlobBuilder&&(g=new BlobBuilder,g.append(d),a.write(g.getBlob("application/json")))}catch(m){c(m)}},c)},c)})}else k(!1)},read:function(b,d){d=v(d);if(b&&m){var k=this.adapter,g=function(b){a(b);d(!1,b)};f(k,b,function(){k.root.getFile(b,{create:!1},function(a){a.file(function(a){var b=new FileReader;b.onloadend=
function(){d(this.result)};b.onerror=g;b.onabort=g;b.readAsText(a)},g)},g)})}else d(!1)},update:function(a,b,k){this.create(a,b,k)},remove:function(b,d){d=v(d);if(b&&m){var k=this.adapter,g=function(b){a(b);d(!1,b)};f(k,b,function(){k.root.getFile(b,{create:!1},function(a){a.remove(function(){d(!0)},g)},g)})}else d(!1)},init:function(a){return this.isSupported()?(a&&a.size&&(this.size=a.size),this):!1}};t.ns("cache.storage.adapter."+s,p)})(window,window.getNs());
(function(c,t,n){function b(a){s("["+f+" Adapter] "+a)}function a(a){a&&b("Database error: "+(a.message||" No message avaible"))}function l(a){if(!(this instanceof l))return new l(a);this.adapter=null;this.type=f;this.dbName="cache";this.dbVersion="1.0";this.dbTable="offline";this.dbDescription="offline cache";this.dbKey="key";this.init(a)}var f="indexedDatabase",p=t.helpers,s=p.console.log,r=p.utils.callback,q=null,v=c.indexedDB||c.webkitIndexedDB||c.mozIndexedDB||c.OIndexedDB||c.msIndexedDB;l.prototype=
l.fn={isSupported:function(){null===q&&((q=!!v)||b(f+" is not supported"));return q},create:function(m,c,e){e=r(e);if(m&&q){var d=this.dbTable,k=this.dbName,g=this.adapter.transaction([d],"readwrite");m=g.objectStore(d).put({key:m,content:c});g.onerror=function(d){b("Failed to init transaction while creating/updating database entry "+k+" "+d);a(d);e(!1,d)};m.onerror=function(d){b("Failed to create/update database entry "+k+" "+d);a(d);e(!1,d)};m.onsuccess=function(){e(!0)}}else e(!1)},read:function(m,
c){c=r(c);if(m&&q){var e=this.dbTable,d=this.dbName,k=this.adapter.transaction([e],"readonly"),e=k.objectStore(e).get(m);k&&e?(k.onerror=function(g){b("Failed to init transaction while reading database "+d+" "+g);a(g);c(!1,g)},e.onerror=function(g){b("Failed to read database entry "+d+" "+g);a(g);c(!1,g)},e.onsuccess=function(a){a.target.result&&a.target.result.content?c(a.target.result.content):c(!1)}):c(!1)}else c(!1)},update:function(a,b,e){this.create(a,b,e)},remove:function(c,h){h=r(h);if(c&&
q){var e=this.dbTable,d=this.dbName,k=this.adapter.transaction([e],"readwrite"),e=k.objectStore(e).put({key:c,content:""});k.onerror=function(k){b("Failed to init transaction while deleting database entry "+d+" "+k);a(k);h(!1,k)};e.onerror=function(k){b("Failed to delete database entry "+d+" "+k);a(k);h(!1,k)};e.onsuccess=function(){h(!0)}}else h(!1)},open:function(m,h){h||(h=!1);m=r(m);var e=this,d=null,k=null,g=null,f=e.dbName,x=e.dbTable,l=function(a){a||m(!1);b("Try to create test resource");
e.create("test-item",'{test: "test-content"}',function(d){d?e.remove("test-item",function(){b("Test resource created and successfully deleted");m(a)}):m(!1)})},p,y,A,q,t;if(null===e.adapter)if(d=v){c.webkitIndexedDB!==n&&(c.IDBTransaction=c.webkitIDBTransaction,c.IDBKeyRange=c.webkitIDBKeyRange);p=function(a){a.createIndex(e.dbKey,e.dbKey,{unique:!0});a.createIndex("content","content",{unique:!1})};y=function(d){var c=k.result,h,A;e.adapter=c;b("Database request successfully done");e.dbVersion===
c.version||!c.setVersion&&"function"!==typeof c.setVersion?(e.adapter=c,l(c)):(g=d.currentTarget.result.setVersion(e.dbVersion),g.onfailure=function(d){b("Failed to open database: "+f+" "+d);a(d);m(!1)},g.onsuccess=function(d){h=k.result;try{A=h.createObjectStore(x,{keyPath:e.dbKey}),b("Database needs upgrade: "+f+" "+d.oldVersion+" "+d.newVersion),p(A)}catch(c){b("Failed to open database: "+f+" "+c),a(c),m(!1)}})};A=function(a){var d=k.result.createObjectStore(x,{keyPath:e.dbKey});b("Database needs upgrade: "+
f+" "+a.oldVersion+" "+a.newVersion);p(d)};q=function(d){b("Failed to open database: "+f+" "+d);a(d);h||e.open(m,!0);m(!1)};t=function(d){b("Opening database request is blocked! "+f+" "+d);a(d);m(!1)};if(h)try{k=d.open(f,e.dbVersion)}catch(s){b("Could not set version"),a(s),k=d.open(f)}else k=d.open(f);k.onsuccess=y;k.onupgradeneeded=A;k.onerror=q;k.onblocked=t}else m(!1);else l(e.adapter)},init:function(a){return this.isSupported()?(a&&(a.name&&(this.dbName=String(a.name)),a.version&&(this.dbVersion=
parseInt(a.version,10)),a.table&&(this.dbTable=a.table),a.description&&(this.dbDescription=String(a.description)),a.key&&(this.dbKey=a.key)),this):!1}};t.ns("cache.storage.adapter."+f,l)})(window,window.getNs());
(function(c,t,n){function b(a){s("["+p+" Adapter] "+a)}function a(a,b,c,d,k,g){!g&&a?a.transaction(function(a){a.executeSql(b,c,d,k)}):g?g.executeSql(b,c,d,k):k(null,{code:0,message:p+" isn't available"})}function l(a){var c="Errorcode: "+(a.code||"Code not present")+", Message: "+(a.message||"Message not present");a.info&&(c=c+" - "+a.info);b(c)}function f(a){if(!(this instanceof f))return new f(a);this.adapter=null;this.type=p;this.dbName="cache";this.dbVersion="1.0";this.dbDescription="resource cache";
this.dbTable="websql";this.dbSize=4194304;this.init(a)}var p="webSqlDatabase";n=t.helpers;var s=n.console.log,r=n.utils.callback,q=null,v=c.openDatabase;f.prototype=f.fn={isSupported:function(){null===q&&((q=!!v)||b(p+" is not supported"));return q},create:function(b,c,e){e=r(e);b&&q?a(this.adapter,"INSERT INTO "+this.dbTable+" (key, content) VALUES (?,?);",[b,c],function(){e(!0)},function(a,b){l(b);e(!1,b,{transaction:a})}):e(!1)},read:function(b,c){c=r(c);b&&q?a(this.adapter,"SELECT content FROM "+
this.dbTable+" WHERE key=?;",[b],function(a,b){var k=!1;b&&(b.rows&&1===b.rows.length)&&(k=b.rows.item(0).content);c(k,null,{transaction:a})},function(a,b){l(b);c(!1,b,{transaction:a})}):c(!1)},update:function(b,c,e){e=r(e);b&&q?a(this.adapter,"UPDATE "+this.dbTable+" SET content = ?  WHERE key=?;",[c,b],function(){e(!0)},function(a,b){l(b);e(!1,b,{transaction:a})}):e(!1)},remove:function(b,c){c=r(c);b&&q?a(this.adapter,"DELETE FROM "+this.dbTable+" WHERE key = ?;",[b],function(){c(!0)},function(a,
b){l(b);c(!1,b,{transaction:a})}):c(!1)},open:function(f){f=r(f);if(q){var h=this,e=h.adapter,d,k=function(a){a||f(!1);b("Try to create test resource");d=function(d){d?h.remove("test-item",function(){b("Test resource created and successfully deleted");f(a)}):f(!1)};h.read("test-item",function(a){a?h.update("test-item",'{test: "test-content"}',d):h.create("test-item",'{test: "test-content"}',d)})},g=function(d,c){b("Checking database table: name "+h.dbTable);a(d,"CREATE TABLE IF NOT EXISTS "+h.dbTable+
"(id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, key TEXT NOT NULL UNIQUE, content TEXT NOT NULL);",[],function(){k(h.adapter)},function(a){l(a);k(!1)},c)},u=function(a){g(null,a)},x=function(a){a.info="Can't migrate to new database version. This may be caused by non-standard implementation of the changeVersion method. Please switch back your database version to use webSql on this device.";l(a);f(!1)};try{if(null===e&&h.isSupported())if(b("Initializing database"),h.adapter=e=v(h.dbName,"",h.dbDescription,
h.dbSize),String(e.version)!==String(h.dbVersion)&&e.changeVersion&&"function"===typeof e.changeVersion){b("Try to update version: new version "+e.version+", old version "+h.dbVersion);try{e.changeVersion(e.version,h.dbVersion,u,x)}catch(n){l(n),f(!1)}}else b("Open database with version number: "+h.dbVersion),e=c.openDatabase(h.dbName,h.dbVersion,h.dbDescription,h.dbSize),g(e);else h.isSupported()&&(b("database already initialized"),k(e))}catch(p){l(p),f(!1)}}else f(!1)},init:function(a){return this.isSupported()?
(a&&(a.description&&(this.dbDescription=a.description),a.name&&(this.dbName=a.name),a.size&&(this.dbSize=a.size),a.table&&(this.dbTable=a.table),a.version&&(this.dbVersion=String(a.version))),this):!1}};t.ns("cache.storage.adapter."+p,f)})(window,window.getNs());
(function(c,t,n){function b(a){v("["+p+" Adapter] "+a)}function a(a){!a&&c.event&&(a=c.event);b("Event - key: "+(a.key||"no e.key event")+", url: "+(a.url||"no e.url event"))}function l(a){a=m(a);switch(a){case "local":a="localStorage";break;case "session":a="sessionStorage";break;default:a="localStorage"}return a}function f(a){if(!(this instanceof f))return new f(a);this.adapter=null;this.type=p;this.lifetime="local";this.asynch=!0;this.init(a)}var p="webStorage",s=t.helpers,r=s.utils,q=s.events.on,
v=s.console.log,m=r.trim,h=r.callback,e=null;f.prototype=f.fn={isSupported:function(){var a=l(this.lifetime);if(null===e)try{e=!!c[a]&&!!c[a].getItem}catch(k){b(p+" is not supported",k),e=!1}return e},create:function(b,c,g){var e=this,f=!0,l=function(a){if(e.asynch)g(a);else return a};g=h(g);if(!b)return l(!1);try{e.adapter.setItem(b,c)}catch(m){f=!f,a(m)}return l(f)},read:function(b,c){var e=this,f,l=!0,m=function(a){if(e.asynch)c(a);else return a};c=h(c);if(!b)return m(!1);try{l=(f=e.adapter.getItem(b))?
f:!1}catch(n){l=!l,a(n)}return m(l)},update:function(a,b,c){if(this.asynch)this.create(a,b,c);else return this.create(a,b,c)},remove:function(b,c){var e=this,f=!0,l=function(a){if(e.asynch)c(a);else return a};c=h(c);if(!b)return l(!1);try{e.adapter.removeItem(b)}catch(m){f=!f,a(m)}return l(f)},open:function(d){var e=this,g=e.adapter,f=l(e.lifetime),m,n,p=function(a){if(e.asynch)d(a);else return a};d=h(d);if(null===g)try{if(g=e.adapter=c[f],q(c,"storage",a),b("Lifetime used: "+f),b("Try to create test resource"),
e.asynch)e.create("test-item",'{test: "test-content"}',function(a){a?e.remove("test-item",function(){b("Test resource created and successfully deleted");d(g)}):d(!1)});else{if(m=e.create("test-item",'{test: "test-content"}'))if(n=e.remove("test-item"))return b("Test resource created and successfully deleted"),g;return!1}}catch(r){return a(r),p(!1)}else if(e.isSupported())return p(g)},init:function(a){return this.isSupported()?(a&&(a.lifetime&&(this.lifetime=m(String(a.lifetime))),a.asynch!==n&&(this.asynch=
!!a.asynch)),this):!1}};t.ns("cache.storage.adapter."+p,f)})(window,window.getNs());
(function(c,t,n,b){function a(a){v("["+p+" Adapter] "+a)}function l(b,d){d.isLoaded||(d.isLoaded=!0,d.progressCallback(100),c.setTimeout(function(){b();a("Event loaded")},d.delay))}function f(a){if(!(this instanceof f))return new f(a);this.adapter=null;this.type=p;this.isLoaded=!1;this.delay=0;this.opened=!0;this.message="New version available. Update page?";this.init(a)}var p="applicationCache",s=n.helpers,r=s.dom,q=s.events.on,v=s.console.log,m=s.utils.callback,h=null,e=t.getElementsByTagName("html")[0],
d=c.applicationCache;f.prototype=f.fn={isSupported:function(){null===h&&((h=!!d&&!!r.getAttribute(e,"manifest"))||a(p+" is not supported or there is no manifest html attribute"));return h},open:function(d,e){var f=this,h=f.adapter,n=0,p,r;f.opened=!0;d=m(d);e&&e.progress&&(p=e.progress);p=f.progressCallback=m(p);if(f.isSupported()&&null!==h){r=function(){a("Event updateready");try{h.swapCache()}catch(b){a("Event updateready: swapcache is not available",b)}confirm(f.message)?c.location.reload(!0):
l(d,f);return!1};q(h,"checking",function(){a("Event checking");return!1});q(h,"noupdate",function(){a("Event noupdate");l(d,f);return!1});q(h,"downloading",function(){a("Event downloading");n=0;return!1});q(h,"progress",function(c){a("Event progress");var d=0;f.delay=500;n+=1;d=c&&c.lengthComputable!==b?Math.round(100*c.loaded/c.total):Math.round(100*n/20);p(d);return!1});q(h,"cached",function(){a("Event cached");l(d,f);return!1});q(h,"updateready",function(){r()});q(h,"obsolete",function(){a("Event obsolete");
c.location.reload(!0);return!1});q(h,"error",function(){a("Event error");l(d,f);return!1});switch(h.status){case h.UNCACHED:l(d,f);break;case h.IDLE:l(d,f);break;case h.UPDATEREADY:r();break;case h.OBSOLETE:l(d,f)}q(c,"online",function(){try{h.update()}catch(b){a("Window event online: update cache is not available",b)}});c.setTimeout(function(){f.isLoaded||l(d,f)},12E3)}else l(d,f)},init:function(a){this.isSupported()&&(null===this.adapter&&(this.adapter=d),a&&(a.message&&(this.message=String(a.message)),
a.delay!==b&&(this.delay=parseInt(a.delay,10))));return this}};n.ns("cache.storage.adapter."+p,f)})(window,document,window.getNs());
(function(c,t,n,b){function a(a){A("["+k+" controller] "+a)}function l(b){var c="";b&&(c="Error Event: Description "+(b.description||"no description available"));a(c)}function f(a,b,d){d.timeoutXhr=c.setTimeout(function(){b(!1)},4E3);K(a,function(a){c.clearTimeout(d.timeoutXhr);delete d.timeoutXhr;a?b(a):b(!1)})}function p(b){var c=null;try{c=w.jsonToObject(b)}catch(d){l(d),a("Couldn't convert json string to object.")}return c}function s(a,c,d){if(I){var e=t.createElement("canvas"),f,g=new Image,
k=null,h=0,l=0;d||(d="jpeg");g.onerror=function(){g.onload=g.onerror=null;c()};g.onload=function(){g.onload=g.onerror=null;h=e.height=g.height;l=e.width=g.width;f=e.getContext("2d");f.fillStyle="rgba(50, 50, 50, 0)";f.fillRect(0,0,l,h);f.drawImage(g,0,0);k=e.toDataURL("image/"+d);c(k)};g.src="";g.src=a;if(g.complete&&g.naturalWidth!==b)g.onload()}else c(!1)}function r(a){var b=a.data,c=a.url;"css"===a.type&&(c=x.url(c),c=c.folder,b=b.replace(/url\(\../g,"url("+c+".."),b=b.replace(/url\(\'../g,"url('"+
c+".."),b=b.replace(/url\(\"../g,'url("'+c+".."),a.data=b);return a}function q(a,c){return{ajax:a.ajax,data:a.data,expires:(new Date).getTime()+(a.lifetime||c.lifetime),group:a.group!==b?a.group:c.group,lastmod:a.lastmod||c.lastmod,lifetime:a.lifetime!==b?a.lifetime:c.lifetime,type:a.type||c.type,version:a.version||c.version}}function v(a,b,c){var d=a.type,e=a.url,g=a.data;a.ajax?"img"===d?s(e,b):f(e,b,a):g?b(g):c(!1)}function m(a){return D&&D[a]?!!D[a]:!1}function h(b,c){var d=null,e,f;b&&b.length?
(e=b[0].type,f=b.slice(1),a("Testing for storage adapter type: "+e),B[e]?d=new B[e](F):h(f,c),d&&d.isSupported()?d.open(function(g){g?(E=e,D=b[0],a("Used storage adapter type: "+E),c(d)):h(f,c)}):h(f,c)):c(!1)}function e(b,c,d){var f=null,g=0,k;if(d)try{a("Testing for preferred storage adapter type: "+d),B[d]?(f=new B[d](F))&&f.isSupported()?f.open(function(h){if(h){E=d;k=c.length;for(g=0;g<k;g+=1)c[g].type===d&&(D=c[g]);D?(a("Used storage type: "+E),b(f)):(a("Storage config not found: "+E),e(b,c))}else e(b,
c)}):e(b,c):e(b,c)}catch(m){l(m),a("Storage adapter could not be initialized: type "+d),e(b,c)}else h(c,b)}function d(a,b){if(!(this instanceof d))return new d(a,b);this.isEnabled=!0;this.appCacheAdapter=this.adapter=null;this.adapters={types:J,defaults:F};this.resources={defaults:L};this.init(a,b)}var k="storage",g=n.helpers,u=g.client,x=g.utils,w=g.json,G=g.ajax,y=x.isArray,A=g.console.log,C=x.callback,H=w.getJson(),K=G.xhr,z=x.trim,B=n.cache.storage.adapter,I=u.hasCanvas(),J=[{type:"fileSystem",
css:!0,js:!0,html:!0,img:!0},{type:"indexedDatabase",css:!0,js:!0,html:!0,img:!0},{type:"webSqlDatabase",css:!0,js:!0,html:!0,img:!0},{type:"webStorage",css:!0,js:!0,html:!0,img:!0}],F={name:"localcache",table:"cache",description:"local resource cache",size:4194304,version:"1.0",key:"key",lifetime:"local",offline:!0},E=null,D=null,L={ajax:!0,lifetime:2E4,group:0,lastmod:(new Date).getTime(),type:"css",version:1};d.prototype=d.fn={create:function(b,c){c=C(c);if(b&&b.url){var d=this,e=b.url,f=b.type;
v(b,function(g){if(g)if(b.data=g,b=r(b),null!==d.adapter&&m(f)){g=w.jsonToString(e);var k=q(b,d.resources.defaults),h=w.jsonToString(k);b.expires=k.expires;b.version=k.version;try{d.adapter.create(g,h,function(d){d?(a("Create new resource in storage adapter: type "+f+", url "+e),c(b)):(a("Create new resource in storage adapter failed"),c(!1))})}catch(n){l(n),a("Create new resource in storage adapter failed"),c(b)}}else a("Trying to create new resource, but resource type is not cachable or storage adapter is not available: type "+
f+", url "+e),c(b);else a("Couldn't get data via network"),c(b)},c)}else c(!1)},read:function(b,c){c=C(c);if(b&&b.url){var d=this,e=b.url,g=b.type;if(null!==this.adapter&&m(g)){a("Trying to read resource from storage: type "+g+", url "+e);try{d.adapter.read(w.jsonToString(e),function(f){f?(b=p(f))?(b.url=e,a("Successfully read resource from storage: type "+g+", url "+e),c(b,!0)):d.remove({url:e,type:g},function(){c(!1)}):(a("There is no data coming back from storage while reading: type "+g+", url "+
e),c(!1))})}catch(k){l(k),a("Try to read resource from storage, but storage adapter is not available: type "+g+", url "+e),f(e,function(d){a("Data loaded via ajax: type "+g+", url "+e+", data status "+!!d);b.data=d;c(b,!0)},b)}}else c(b)}else c(!1)},update:function(b,c){c=C(c);if(b&&b.url){var d=this,e=b.url,f=b.type;v(b,function(g){if(g)if(b.data=g,b=r(b),null!==d.adapter&&m(f)){g=w.jsonToString(e);var k=q(b,d.resources.defaults),h=w.jsonToString(k);b.expires=k.expires;b.version=k.version;try{d.adapter.update(g,
h,function(d){d?(a("Updated existing resource in storage adapter: type "+f+", url "+e),c(b)):(a("Updating resource in storage failed."),c(!1))})}catch(n){l(n),a("Updating resource in storage failed."),c(b)}}else a("Resource type is not cachable or storage adapter is not available: type "+f+", url "+e),c(b);else a("Couldn't get data via network, trying to used stored version"),d.read(b,function(a){a&&a.data?(b.data=a.data,c(b)):c(!1)})},c)}else c(!1)},remove:function(b,c){c=C(c);if(b&&b.url){var d=
b.url,e=b.type;null!==this.adapter&&m(e)?this.adapter.remove(w.jsonToString(d),function(f){f?(a("Delete resource form storage: type "+e+", url "+d),c(b)):(a("Deleting resource form storage failed: type "+e+", url "+d),c(!1))}):(a("Delete resource from storage failed, resource type is not cachable or there is no storage adapter: type "+e+", url "+d),c(b))}else c(!1)},init:function(c,d){var f=this,g=!1,k,h,l,m;c=C(c);d&&d.isEnabled!==b&&(f.isEnabled=!!d.isEnabled);if(f.isEnabled&&H){if(d){if(d.adapters){k=
d.adapters;if(k.types&&y(k.types)){h=k.types;l=h.length;for(m=0;m<l;m+=1)h[m].css===b&&(h[m].css=!0),h[m].js===b&&(h[m].js=!0),h[m].img===b&&(h[m].img=!0),h[m].html===b&&(h[m].html=!0);f.adapters.types=h}k.defaults&&(h=k.defaults,l=f.adapters.defaults,h.name&&(l.name=z(String(h.name))),h.table&&(l.table=z(String(h.table))),h.description&&(l.description=z(String(h.description))),h.size&&(l.size=parseInt(h.size,10)),h.version&&(l.version=z(String(h.version))),h.key&&(l.key=z(String(h.key))),h.lifetime&&
(l.lifetime=z(String(h.lifetime))),h.offline!==b&&(l.offline=!!h.offline));k.preferredType&&(g=z(String(k.preferredType)))}d.resources&&(k=d.resources,k.defaults&&(k=k.defaults,h=f.resources.defaults,k.ajax!==b&&(h.ajax=!!k.ajax),k.lifetime!==b&&(h.lifetime=parseInt(k.lifetime,10)),k.group!==b&&(h.group=parseInt(k.group,10)),k.lastmod!==b&&(h.lastmod=parseInt(k.lastmod,10)),k.type&&(h.type=z(String(k.type))),k.group!==b&&(h.version=parseFloat(k.version)),k.loaded&&(h.loaded=C(k.loaded))))}e(function(a){a||
(f.isEnabled=!1);f.adapter=a;c(f)},f.adapters.types,g);f.adapters.defaults.offline&&(B.applicationCache&&!f.appCacheAdapter)&&(f.appCacheAdapter=new B.applicationCache(F))}else H||a("There is no json support"),f.isEnabled||a("Caching data is disabled"),c(f)}};n.ns("cache."+k+".controller",d)})(window,document,window.getNs());
(function(c,t){function n(a){q("["+l+" controller] "+a)}function b(a){var b=m(a.type);if("js"!==b||"css"!==b||"html"!==b||"img"!==b||"custom"!==b){switch(s.url(a.url).extension){case "js":a="js";break;case "css":a="css";break;case "html":a="html";break;case "jpg":case "jpeg":case "png":a="img";break;default:a="custom"}b=a}return b}function a(b,c){if(!(this instanceof a))return new a(b,c);this.storage=null;this.init(b,c)}var l="cache",f=c.helpers,p=f.dom,s=f.utils,r=f.client,q=f.console.log,v=s.isArray,
m=s.trim,h=s.callback;a.prototype=a.fn={load:function(a,c){var f=this,g=(new Date).getTime(),l=function(){var a=0,b=0,c=null;return{init:function(d,f){c=f;a=d;b=0},loaded:function(){b+=1;b===a&&c()}}}(),q=function(a,b,c){var d=a.url,f=function(){a.loaded(a);l.loaded()},e=a.node||null;c=!!c;switch(a.type){case "js":p.appendJs(d,b,f,e,c);break;case "css":p.appendCss(d,b,f,e,c);break;case "img":p.appendImg(d,b,f,e,c);break;case "html":p.appendHtml(d,b,f,e,c);break;default:n("Didn't match any type for dom append: type "+
a.type),f()}},s=function(a){var b=a.data||null,c=function(a,b){a&&a.data?q(a,a.data,b):q(a,null,b)},d=f.storage,e=d.resources.defaults;a.ajax=a.ajax!==t?!!a.ajax:e.ajax;a.loaded=a.loaded!==t?h(a.loaded):h(e.loaded);d.read(a,function(e){if(e&&e.data){var h=a,l=f.storage.resources.defaults,m=parseInt(e.lifetime,10),p=e.version,s=e.lastmod?e.lastmod:0,y=!1,w,u=h.lastmod?h.lastmod:0,y=!0;w=!1;h.version=w=h.version!==t?parseFloat(h.version):l.version;h.group=h.group!==t?parseFloat(h.group):l.group;u&&
s?(h.lastmod=parseInt(u,10),y=s===h.lastmod):!u&&s?u=s:u||(u=l.lastmod);y=y&&w===p;w=0!==m&&(-1!==m&&y&&e.expires>g||-1===m&&y);h.lastmod=u;h.isValid=w;a=h;a.isValid||!r.isOnline()?(n("Resource is up to date: type "+a.type+", url "+a.url),(b=e.data)&&q(a,b)):(n("Resource is outdated and needs update: type "+a.type+", url "+a.url),d.update(a,c))}else n("Resource or resource data is not available in storage adapter, try to create it: type "+a.type+", url "+a.url),d.create(a,c)})},G=function(a,c){var d=
0,e=a.length,f=null;l.init(e,c);for(d=0;d<e;d+=1)(f=a[d])&&f.url&&(f.url=m(f.url),f.type=b(f),s(f))},y=function(a,b,c){var d=a.length;for(c||(c=0);!a[c]&&c<d;)c+=1;c>=d?b(f):(d=a[c],G(d,function(){y(a,b,c+1)}))};(function(a,b){var f;a&&v(a)||(a=[]);f=a.length;for(var e=a,g=[],k,l=0,m,p=e.length,l=0;l<p;l+=1)m=e[l],(k=m.group)||(k=0),k=g[k]?g[k]:g[k]=[],k.push(m);a=g;b=h(c);n("Load resource function called: "+f+" resources, "+a.length+" groups");y(a,b)})(a,c)},remove:function(a,c){var f=this.storage,
g=function(a,c){var d=a.length,e,g,h=function(a,b){n("Successfully removed resource: url "+b);a===d-1&&c()};if(d)for(e=0;e<d;e+=1)(g=a[e])&&g.url&&(g.url=m(g.url),g.type=b(g),f.remove(g,h(e,g.url)));else c()};(function(a,b){a&&v(a)||(a=[]);b=h(c);n("Remove resource function called: resources count "+a.length);g(a,b)})(a,c)},init:function(a,b){var f=this;a=h(a);n("Cache initializing, checking for storage and adapters");c.cache.storage.controller(function(b){f.storage=b;a(b)},b);return f}};c.ns(l+".controller",
a)})(window.getNs());
(function(c,t,n){function b(a){v("[cache interface] "+a)}function a(a){this.storage=this.controller=null;this.params=a;this.queue=new s;this.timeout=this.interval=this.calls=0}function l(b){var c=null,d=p.length,f;b||(b=u);if(h)for(f=0;f<d;f+=1)e(p[f].params)===e(b)&&(c=p[f]);c||(c=new a(b),p.push(c));return c}function f(a,d,f){var e=l(a),h,m,n,p=function(){h=e.interval;c.clearInterval(h);h=c.setInterval(function(){e.timeout=m=e.timeout+k;n=e.storage;e.controller&&(n&&(n.adapter||!n.isEnabled))&&
(c.clearInterval(h),e.queue.flush());m>g&&(c.clearInterval(h),b("Timeout reached while waiting for cache controller!!!"),f())},k)};e?e.storage?d(e):(e.queue.add(function(){d(e)}),e.calls+=1,1===e.calls?e.controller=new t.cache.controller(function(a){e.storage=a;e.controller?e.queue.flush():p()},a):p()):(b("Whether finding nor initializing a cache interface is possible!!!"),f())}var p=[];n=t.helpers;var s=n.queue,r=n.utils,q=n.json,v=n.console.log,m=r.isArray,h=q.getJson(),e=q.jsonToString,d=r.callback,
k=15,g=5E3,u={};n=function(){return{load:function(a,c,e){c=d(c);f(e,function(b){m(a)?b.controller.load(a,c):"applicationCache"===a?(b=b.storage)&&b.appCacheAdapter?b.appCacheAdapter.open(c,e):c(!1):c(!1)},function(){b("Get interface failed!");c(!1)});return this},remove:function(a,c,e){c=d(c);f(e,function(b){m(a)?b.controller.remove(a,c):c(!1)},function(){b("Get interface failed!");c(!1)});return this},setup:function(a){a&&(u=a);return this}}}();t.ns("cache.load",n.load);t.ns("cache.remove",n.remove);
t.ns("cache.setup",n.setup)})(window,window.getNs());
